//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgPlayerInfo.proto
namespace PBMsgPlayerInfo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgPlayerInfo")]
  public partial class PBMsgPlayerInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgPlayerInfo() {}
    
    private string _pveVer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pveVer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pveVer
    {
      get { return _pveVer?? ""; }
      set { _pveVer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pveVerSpecified
    {
      get { return this._pveVer != null; }
      set { if (value == (this._pveVer== null)) this._pveVer = value ? this.pveVer : (string)null; }
    }
    private bool ShouldSerializepveVer() { return pveVerSpecified; }
    private void ResetpveVer() { pveVerSpecified = false; }
    
    private byte[] _pveInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pveInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] pveInfo
    {
      get { return _pveInfo?? null; }
      set { _pveInfo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pveInfoSpecified
    {
      get { return this._pveInfo != null; }
      set { if (value == (this._pveInfo== null)) this._pveInfo = value ? this.pveInfo : (byte[])null; }
    }
    private bool ShouldSerializepveInfo() { return pveInfoSpecified; }
    private void ResetpveInfo() { pveInfoSpecified = false; }
    
    private string _heroVer;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"heroVer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string heroVer
    {
      get { return _heroVer?? ""; }
      set { _heroVer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool heroVerSpecified
    {
      get { return this._heroVer != null; }
      set { if (value == (this._heroVer== null)) this._heroVer = value ? this.heroVer : (string)null; }
    }
    private bool ShouldSerializeheroVer() { return heroVerSpecified; }
    private void ResetheroVer() { heroVerSpecified = false; }
    
    private byte[] _heroInfo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"heroInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] heroInfo
    {
      get { return _heroInfo?? null; }
      set { _heroInfo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool heroInfoSpecified
    {
      get { return this._heroInfo != null; }
      set { if (value == (this._heroInfo== null)) this._heroInfo = value ? this.heroInfo : (byte[])null; }
    }
    private bool ShouldSerializeheroInfo() { return heroInfoSpecified; }
    private void ResetheroInfo() { heroInfoSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}