//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAvaTileTroops.proto
namespace PBMsgAvaTileTroops
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAvaTileTroops")]
  public partial class PBMsgAvaTileTroops : global::ProtoBuf.IExtensible
  {
    public PBMsgAvaTileTroops() {}
    
    private int _tileId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tileId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileId
    {
      get { return _tileId; }
      set { _tileId = value; }
    }
    private int _tileType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tileType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileType
    {
      get { return _tileType; }
      set { _tileType = value; }
    }
    private int _xCoord;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"xCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xCoord
    {
      get { return _xCoord; }
      set { _xCoord = value; }
    }
    private int _yCoord;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"yCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int yCoord
    {
      get { return _yCoord; }
      set { _yCoord = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _playerName;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private readonly global::System.Collections.Generic.List<PBMsgAvaTileTroops.MarchInfo> _marchList = new global::System.Collections.Generic.List<PBMsgAvaTileTroops.MarchInfo>();
    [global::ProtoBuf.ProtoMember(7, Name=@"marchList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAvaTileTroops.MarchInfo> marchList
    {
      get { return _marchList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Unit")]
  public partial class Unit : global::ProtoBuf.IExtensible
  {
    public Unit() {}
    
    private int? _unitId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unitId
    {
      get { return _unitId?? default(int); }
      set { _unitId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool unitIdSpecified
    {
      get { return this._unitId != null; }
      set { if (value == (this._unitId== null)) this._unitId = value ? this.unitId : (int?)null; }
    }
    private bool ShouldSerializeunitId() { return unitIdSpecified; }
    private void ResetunitId() { unitIdSpecified = false; }
    
    private int? _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroInfo")]
  public partial class HeroInfo : global::ProtoBuf.IExtensible
  {
    public HeroInfo() {}
    
    private int? _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId?? default(int); }
      set { _heroId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool heroIdSpecified
    {
      get { return this._heroId != null; }
      set { if (value == (this._heroId== null)) this._heroId = value ? this.heroId : (int?)null; }
    }
    private bool ShouldSerializeheroId() { return heroIdSpecified; }
    private void ResetheroId() { heroIdSpecified = false; }
    
    private int? _heroTypeId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroTypeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroTypeId
    {
      get { return _heroTypeId?? default(int); }
      set { _heroTypeId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool heroTypeIdSpecified
    {
      get { return this._heroTypeId != null; }
      set { if (value == (this._heroTypeId== null)) this._heroTypeId = value ? this.heroTypeId : (int?)null; }
    }
    private bool ShouldSerializeheroTypeId() { return heroTypeIdSpecified; }
    private void ResetheroTypeId() { heroTypeIdSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MarchInfo")]
  public partial class MarchInfo : global::ProtoBuf.IExtensible
  {
    public MarchInfo() {}
    
    private int _marchId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marchId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchId
    {
      get { return _marchId; }
      set { _marchId = value; }
    }
    private int _marchType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"marchType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchType
    {
      get { return _marchType; }
      set { _marchType = value; }
    }
    private int _marchStatus;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"marchStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchStatus
    {
      get { return _marchStatus; }
      set { _marchStatus = value; }
    }
    private int _fromPlayerId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"fromPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromPlayerId
    {
      get { return _fromPlayerId; }
      set { _fromPlayerId = value; }
    }
    private string _fromPlayerName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"fromPlayerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fromPlayerName
    {
      get { return _fromPlayerName; }
      set { _fromPlayerName = value; }
    }
    private int? _fromXCoord;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fromXCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromXCoord
    {
      get { return _fromXCoord?? default(int); }
      set { _fromXCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromXCoordSpecified
    {
      get { return this._fromXCoord != null; }
      set { if (value == (this._fromXCoord== null)) this._fromXCoord = value ? this.fromXCoord : (int?)null; }
    }
    private bool ShouldSerializefromXCoord() { return fromXCoordSpecified; }
    private void ResetfromXCoord() { fromXCoordSpecified = false; }
    
    private int? _fromYCoord;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fromYCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromYCoord
    {
      get { return _fromYCoord?? default(int); }
      set { _fromYCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromYCoordSpecified
    {
      get { return this._fromYCoord != null; }
      set { if (value == (this._fromYCoord== null)) this._fromYCoord = value ? this.fromYCoord : (int?)null; }
    }
    private bool ShouldSerializefromYCoord() { return fromYCoordSpecified; }
    private void ResetfromYCoord() { fromYCoordSpecified = false; }
    
    private int? _knightId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"knightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int knightId
    {
      get { return _knightId?? default(int); }
      set { _knightId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightIdSpecified
    {
      get { return this._knightId != null; }
      set { if (value == (this._knightId== null)) this._knightId = value ? this.knightId : (int?)null; }
    }
    private bool ShouldSerializeknightId() { return knightIdSpecified; }
    private void ResetknightId() { knightIdSpecified = false; }
    
    private int? _cityOrder;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"cityOrder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cityOrder
    {
      get { return _cityOrder?? default(int); }
      set { _cityOrder = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cityOrderSpecified
    {
      get { return this._cityOrder != null; }
      set { if (value == (this._cityOrder== null)) this._cityOrder = value ? this.cityOrder : (int?)null; }
    }
    private bool ShouldSerializecityOrder() { return cityOrderSpecified; }
    private void ResetcityOrder() { cityOrderSpecified = false; }
    
    private string _knightName;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"knightName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string knightName
    {
      get { return _knightName?? ""; }
      set { _knightName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightNameSpecified
    {
      get { return this._knightName != null; }
      set { if (value == (this._knightName== null)) this._knightName = value ? this.knightName : (string)null; }
    }
    private bool ShouldSerializeknightName() { return knightNameSpecified; }
    private void ResetknightName() { knightNameSpecified = false; }
    
    private int? _knightLevel;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"knightLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int knightLevel
    {
      get { return _knightLevel?? default(int); }
      set { _knightLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightLevelSpecified
    {
      get { return this._knightLevel != null; }
      set { if (value == (this._knightLevel== null)) this._knightLevel = value ? this.knightLevel : (int?)null; }
    }
    private bool ShouldSerializeknightLevel() { return knightLevelSpecified; }
    private void ResetknightLevel() { knightLevelSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<PBMsgAvaTileTroops.Unit> _unitList = new global::System.Collections.Generic.List<PBMsgAvaTileTroops.Unit>();
    [global::ProtoBuf.ProtoMember(12, Name=@"unitList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAvaTileTroops.Unit> unitList
    {
      get { return _unitList; }
    }
  
    private readonly global::System.Collections.Generic.List<PBMsgAvaTileTroops.HeroInfo> _heroList = new global::System.Collections.Generic.List<PBMsgAvaTileTroops.HeroInfo>();
    [global::ProtoBuf.ProtoMember(13, Name=@"heroList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAvaTileTroops.HeroInfo> heroList
    {
      get { return _heroList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}