//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAVATroop.proto
namespace PBMsgAVATroop
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAVATroop")]
  public partial class PBMsgAVATroop : global::ProtoBuf.IExtensible
  {
    public PBMsgAVATroop() {}
    
    private readonly global::System.Collections.Generic.List<PBMsgAVATroop.Knight> _knights = new global::System.Collections.Generic.List<PBMsgAVATroop.Knight>();
    [global::ProtoBuf.ProtoMember(1, Name=@"knights", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAVATroop.Knight> knights
    {
      get { return _knights; }
    }
  
    private readonly global::System.Collections.Generic.List<PBMsgAVATroop.Hero> _heros = new global::System.Collections.Generic.List<PBMsgAVATroop.Hero>();
    [global::ProtoBuf.ProtoMember(2, Name=@"heros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAVATroop.Hero> heros
    {
      get { return _heros; }
    }
  
    private readonly global::System.Collections.Generic.List<PBMsgAVATroop.Unit> _units = new global::System.Collections.Generic.List<PBMsgAVATroop.Unit>();
    [global::ProtoBuf.ProtoMember(3, Name=@"units", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAVATroop.Unit> units
    {
      get { return _units; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Hero")]
  public partial class Hero : global::ProtoBuf.IExtensible
  {
    public Hero() {}
    
    private int? _userHeroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userHeroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userHeroId
    {
      get { return _userHeroId?? default(int); }
      set { _userHeroId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool userHeroIdSpecified
    {
      get { return this._userHeroId != null; }
      set { if (value == (this._userHeroId== null)) this._userHeroId = value ? this.userHeroId : (int?)null; }
    }
    private bool ShouldSerializeuserHeroId() { return userHeroIdSpecified; }
    private void ResetuserHeroId() { userHeroIdSpecified = false; }
    
    private int? _heroId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId?? default(int); }
      set { _heroId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool heroIdSpecified
    {
      get { return this._heroId != null; }
      set { if (value == (this._heroId== null)) this._heroId = value ? this.heroId : (int?)null; }
    }
    private bool ShouldSerializeheroId() { return heroIdSpecified; }
    private void ResetheroId() { heroIdSpecified = false; }
    
    private int? _status;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status?? default(int); }
      set { _status = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool statusSpecified
    {
      get { return this._status != null; }
      set { if (value == (this._status== null)) this._status = value ? this.status : (int?)null; }
    }
    private bool ShouldSerializestatus() { return statusSpecified; }
    private void Resetstatus() { statusSpecified = false; }
    
    private int? _sleepStartTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sleepStartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sleepStartTime
    {
      get { return _sleepStartTime?? default(int); }
      set { _sleepStartTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sleepStartTimeSpecified
    {
      get { return this._sleepStartTime != null; }
      set { if (value == (this._sleepStartTime== null)) this._sleepStartTime = value ? this.sleepStartTime : (int?)null; }
    }
    private bool ShouldSerializesleepStartTime() { return sleepStartTimeSpecified; }
    private void ResetsleepStartTime() { sleepStartTimeSpecified = false; }
    
    private int? _sleepEndTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sleepEndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sleepEndTime
    {
      get { return _sleepEndTime?? default(int); }
      set { _sleepEndTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sleepEndTimeSpecified
    {
      get { return this._sleepEndTime != null; }
      set { if (value == (this._sleepEndTime== null)) this._sleepEndTime = value ? this.sleepEndTime : (int?)null; }
    }
    private bool ShouldSerializesleepEndTime() { return sleepEndTimeSpecified; }
    private void ResetsleepEndTime() { sleepEndTimeSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private int? _sleepTotal;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sleepTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sleepTotal
    {
      get { return _sleepTotal?? default(int); }
      set { _sleepTotal = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sleepTotalSpecified
    {
      get { return this._sleepTotal != null; }
      set { if (value == (this._sleepTotal== null)) this._sleepTotal = value ? this.sleepTotal : (int?)null; }
    }
    private bool ShouldSerializesleepTotal() { return sleepTotalSpecified; }
    private void ResetsleepTotal() { sleepTotalSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Knight")]
  public partial class Knight : global::ProtoBuf.IExtensible
  {
    public Knight() {}
    
    private int? _knightId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"knightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int knightId
    {
      get { return _knightId?? default(int); }
      set { _knightId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightIdSpecified
    {
      get { return this._knightId != null; }
      set { if (value == (this._knightId== null)) this._knightId = value ? this.knightId : (int?)null; }
    }
    private bool ShouldSerializeknightId() { return knightIdSpecified; }
    private void ResetknightId() { knightIdSpecified = false; }
    
    private string _knightName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"knightName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string knightName
    {
      get { return _knightName?? ""; }
      set { _knightName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightNameSpecified
    {
      get { return this._knightName != null; }
      set { if (value == (this._knightName== null)) this._knightName = value ? this.knightName : (string)null; }
    }
    private bool ShouldSerializeknightName() { return knightNameSpecified; }
    private void ResetknightName() { knightNameSpecified = false; }
    
    private int? _cityOrder;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cityOrder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cityOrder
    {
      get { return _cityOrder?? default(int); }
      set { _cityOrder = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cityOrderSpecified
    {
      get { return this._cityOrder != null; }
      set { if (value == (this._cityOrder== null)) this._cityOrder = value ? this.cityOrder : (int?)null; }
    }
    private bool ShouldSerializecityOrder() { return cityOrderSpecified; }
    private void ResetcityOrder() { cityOrderSpecified = false; }
    
    private int? _knightLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"knightLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int knightLevel
    {
      get { return _knightLevel?? default(int); }
      set { _knightLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightLevelSpecified
    {
      get { return this._knightLevel != null; }
      set { if (value == (this._knightLevel== null)) this._knightLevel = value ? this.knightLevel : (int?)null; }
    }
    private bool ShouldSerializeknightLevel() { return knightLevelSpecified; }
    private void ResetknightLevel() { knightLevelSpecified = false; }
    
    private int? _knightStatus;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"knightStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int knightStatus
    {
      get { return _knightStatus?? default(int); }
      set { _knightStatus = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightStatusSpecified
    {
      get { return this._knightStatus != null; }
      set { if (value == (this._knightStatus== null)) this._knightStatus = value ? this.knightStatus : (int?)null; }
    }
    private bool ShouldSerializeknightStatus() { return knightStatusSpecified; }
    private void ResetknightStatus() { knightStatusSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Unit")]
  public partial class Unit : global::ProtoBuf.IExtensible
  {
    public Unit() {}
    
    private int? _unitId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unitId
    {
      get { return _unitId?? default(int); }
      set { _unitId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool unitIdSpecified
    {
      get { return this._unitId != null; }
      set { if (value == (this._unitId== null)) this._unitId = value ? this.unitId : (int?)null; }
    }
    private bool ShouldSerializeunitId() { return unitIdSpecified; }
    private void ResetunitId() { unitIdSpecified = false; }
    
    private long? _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long num
    {
      get { return _num?? default(long); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (long?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}