//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAvaTroopStatus.proto
namespace PBMsgAvaTroopStatus
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAvaTroopStatus")]
  public partial class PBMsgAvaTroopStatus : global::ProtoBuf.IExtensible
  {
    public PBMsgAvaTroopStatus() {}
    
    private int _hideStatus;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hideStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hideStatus
    {
      get { return _hideStatus; }
      set { _hideStatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}