//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgReqAllianceSkillInfo.proto
namespace PBMsgReqAllianceSkillInfo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgReqAllianceSkillInfo")]
  public partial class PBMsgReqAllianceSkillInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgReqAllianceSkillInfo() {}
    
    private long _allianceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"allianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long allianceId
    {
      get { return _allianceId; }
      set { _allianceId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}