//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAVAMarchList.proto
namespace PBMsgAVAMarchList
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAVAMarchList")]
  public partial class PBMsgAVAMarchList : global::ProtoBuf.IExtensible
  {
    public PBMsgAVAMarchList() {}
    
    private readonly global::System.Collections.Generic.List<PBMsgAVAMarchList.MarchInfo> _marchlist = new global::System.Collections.Generic.List<PBMsgAVAMarchList.MarchInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"marchlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAVAMarchList.MarchInfo> marchlist
    {
      get { return _marchlist; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Unit")]
  public partial class Unit : global::ProtoBuf.IExtensible
  {
    public Unit() {}
    
    private int? _unitId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unitId
    {
      get { return _unitId?? default(int); }
      set { _unitId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool unitIdSpecified
    {
      get { return this._unitId != null; }
      set { if (value == (this._unitId== null)) this._unitId = value ? this.unitId : (int?)null; }
    }
    private bool ShouldSerializeunitId() { return unitIdSpecified; }
    private void ResetunitId() { unitIdSpecified = false; }
    
    private int? _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroInfo")]
  public partial class HeroInfo : global::ProtoBuf.IExtensible
  {
    public HeroInfo() {}
    
    private int? _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId?? default(int); }
      set { _heroId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool heroIdSpecified
    {
      get { return this._heroId != null; }
      set { if (value == (this._heroId== null)) this._heroId = value ? this.heroId : (int?)null; }
    }
    private bool ShouldSerializeheroId() { return heroIdSpecified; }
    private void ResetheroId() { heroIdSpecified = false; }
    
    private int? _heroTypeId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroTypeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroTypeId
    {
      get { return _heroTypeId?? default(int); }
      set { _heroTypeId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool heroTypeIdSpecified
    {
      get { return this._heroTypeId != null; }
      set { if (value == (this._heroTypeId== null)) this._heroTypeId = value ? this.heroTypeId : (int?)null; }
    }
    private bool ShouldSerializeheroTypeId() { return heroTypeIdSpecified; }
    private void ResetheroTypeId() { heroTypeIdSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RallyPlayerInfo")]
  public partial class RallyPlayerInfo : global::ProtoBuf.IExtensible
  {
    public RallyPlayerInfo() {}
    
    private string _playerName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private int _role;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int role
    {
      get { return _role; }
      set { _role = value; }
    }
    private int? _ownerXCoord;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ownerXCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ownerXCoord
    {
      get { return _ownerXCoord?? default(int); }
      set { _ownerXCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ownerXCoordSpecified
    {
      get { return this._ownerXCoord != null; }
      set { if (value == (this._ownerXCoord== null)) this._ownerXCoord = value ? this.ownerXCoord : (int?)null; }
    }
    private bool ShouldSerializeownerXCoord() { return ownerXCoordSpecified; }
    private void ResetownerXCoord() { ownerXCoordSpecified = false; }
    
    private int? _ownerYCoord;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ownerYCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ownerYCoord
    {
      get { return _ownerYCoord?? default(int); }
      set { _ownerYCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ownerYCoordSpecified
    {
      get { return this._ownerYCoord != null; }
      set { if (value == (this._ownerYCoord== null)) this._ownerYCoord = value ? this.ownerYCoord : (int?)null; }
    }
    private bool ShouldSerializeownerYCoord() { return ownerYCoordSpecified; }
    private void ResetownerYCoord() { ownerYCoordSpecified = false; }
    
    private int? _arrivalTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"arrivalTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int arrivalTime
    {
      get { return _arrivalTime?? default(int); }
      set { _arrivalTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool arrivalTimeSpecified
    {
      get { return this._arrivalTime != null; }
      set { if (value == (this._arrivalTime== null)) this._arrivalTime = value ? this.arrivalTime : (int?)null; }
    }
    private bool ShouldSerializearrivalTime() { return arrivalTimeSpecified; }
    private void ResetarrivalTime() { arrivalTimeSpecified = false; }
    
    private int? _knightId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"knightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int knightId
    {
      get { return _knightId?? default(int); }
      set { _knightId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightIdSpecified
    {
      get { return this._knightId != null; }
      set { if (value == (this._knightId== null)) this._knightId = value ? this.knightId : (int?)null; }
    }
    private bool ShouldSerializeknightId() { return knightIdSpecified; }
    private void ResetknightId() { knightIdSpecified = false; }
    
    private string _knightName;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"knightName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string knightName
    {
      get { return _knightName?? ""; }
      set { _knightName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightNameSpecified
    {
      get { return this._knightName != null; }
      set { if (value == (this._knightName== null)) this._knightName = value ? this.knightName : (string)null; }
    }
    private bool ShouldSerializeknightName() { return knightNameSpecified; }
    private void ResetknightName() { knightNameSpecified = false; }
    
    private int? _knightCityOrder;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"knightCityOrder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int knightCityOrder
    {
      get { return _knightCityOrder?? default(int); }
      set { _knightCityOrder = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightCityOrderSpecified
    {
      get { return this._knightCityOrder != null; }
      set { if (value == (this._knightCityOrder== null)) this._knightCityOrder = value ? this.knightCityOrder : (int?)null; }
    }
    private bool ShouldSerializeknightCityOrder() { return knightCityOrderSpecified; }
    private void ResetknightCityOrder() { knightCityOrderSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<PBMsgAVAMarchList.HeroInfo> _herolist = new global::System.Collections.Generic.List<PBMsgAVAMarchList.HeroInfo>();
    [global::ProtoBuf.ProtoMember(9, Name=@"herolist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAVAMarchList.HeroInfo> herolist
    {
      get { return _herolist; }
    }
  
    private readonly global::System.Collections.Generic.List<PBMsgAVAMarchList.Unit> _unitlist = new global::System.Collections.Generic.List<PBMsgAVAMarchList.Unit>();
    [global::ProtoBuf.ProtoMember(10, Name=@"unitlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAVAMarchList.Unit> unitlist
    {
      get { return _unitlist; }
    }
  
    private int _playerId;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _marchId;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"marchId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchId
    {
      get { return _marchId; }
      set { _marchId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RallyAttackInfo")]
  public partial class RallyAttackInfo : global::ProtoBuf.IExtensible
  {
    public RallyAttackInfo() {}
    
    private int _rallyNumber;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rallyNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rallyNumber
    {
      get { return _rallyNumber; }
      set { _rallyNumber = value; }
    }
    private int _leaveTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"leaveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leaveTime
    {
      get { return _leaveTime; }
      set { _leaveTime = value; }
    }
    private readonly global::System.Collections.Generic.List<PBMsgAVAMarchList.RallyPlayerInfo> _rallyPlayerList = new global::System.Collections.Generic.List<PBMsgAVAMarchList.RallyPlayerInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rallyPlayerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAVAMarchList.RallyPlayerInfo> rallyPlayerList
    {
      get { return _rallyPlayerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MarchInfo")]
  public partial class MarchInfo : global::ProtoBuf.IExtensible
  {
    public MarchInfo() {}
    
    private int _marchId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marchId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchId
    {
      get { return _marchId; }
      set { _marchId = value; }
    }
    private int _activityid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"activityid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int activityid
    {
      get { return _activityid; }
      set { _activityid = value; }
    }
    private int? _serverid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"serverid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverid
    {
      get { return _serverid?? default(int); }
      set { _serverid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool serveridSpecified
    {
      get { return this._serverid != null; }
      set { if (value == (this._serverid== null)) this._serverid = value ? this.serverid : (int?)null; }
    }
    private bool ShouldSerializeserverid() { return serveridSpecified; }
    private void Resetserverid() { serveridSpecified = false; }
    
    private int? _fromPlayerId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fromPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromPlayerId
    {
      get { return _fromPlayerId?? default(int); }
      set { _fromPlayerId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromPlayerIdSpecified
    {
      get { return this._fromPlayerId != null; }
      set { if (value == (this._fromPlayerId== null)) this._fromPlayerId = value ? this.fromPlayerId : (int?)null; }
    }
    private bool ShouldSerializefromPlayerId() { return fromPlayerIdSpecified; }
    private void ResetfromPlayerId() { fromPlayerIdSpecified = false; }
    
    private string _fromPlayerName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fromPlayerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fromPlayerName
    {
      get { return _fromPlayerName?? ""; }
      set { _fromPlayerName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromPlayerNameSpecified
    {
      get { return this._fromPlayerName != null; }
      set { if (value == (this._fromPlayerName== null)) this._fromPlayerName = value ? this.fromPlayerName : (string)null; }
    }
    private bool ShouldSerializefromPlayerName() { return fromPlayerNameSpecified; }
    private void ResetfromPlayerName() { fromPlayerNameSpecified = false; }
    
    private int? _fromAllianceId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fromAllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromAllianceId
    {
      get { return _fromAllianceId?? default(int); }
      set { _fromAllianceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromAllianceIdSpecified
    {
      get { return this._fromAllianceId != null; }
      set { if (value == (this._fromAllianceId== null)) this._fromAllianceId = value ? this.fromAllianceId : (int?)null; }
    }
    private bool ShouldSerializefromAllianceId() { return fromAllianceIdSpecified; }
    private void ResetfromAllianceId() { fromAllianceIdSpecified = false; }
    
    private int? _fromXCoord;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fromXCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromXCoord
    {
      get { return _fromXCoord?? default(int); }
      set { _fromXCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromXCoordSpecified
    {
      get { return this._fromXCoord != null; }
      set { if (value == (this._fromXCoord== null)) this._fromXCoord = value ? this.fromXCoord : (int?)null; }
    }
    private bool ShouldSerializefromXCoord() { return fromXCoordSpecified; }
    private void ResetfromXCoord() { fromXCoordSpecified = false; }
    
    private int? _fromYCoord;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"fromYCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromYCoord
    {
      get { return _fromYCoord?? default(int); }
      set { _fromYCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromYCoordSpecified
    {
      get { return this._fromYCoord != null; }
      set { if (value == (this._fromYCoord== null)) this._fromYCoord = value ? this.fromYCoord : (int?)null; }
    }
    private bool ShouldSerializefromYCoord() { return fromYCoordSpecified; }
    private void ResetfromYCoord() { fromYCoordSpecified = false; }
    
    private int? _fromTileId;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"fromTileId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromTileId
    {
      get { return _fromTileId?? default(int); }
      set { _fromTileId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromTileIdSpecified
    {
      get { return this._fromTileId != null; }
      set { if (value == (this._fromTileId== null)) this._fromTileId = value ? this.fromTileId : (int?)null; }
    }
    private bool ShouldSerializefromTileId() { return fromTileIdSpecified; }
    private void ResetfromTileId() { fromTileIdSpecified = false; }
    
    private int? _fromTileType;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"fromTileType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromTileType
    {
      get { return _fromTileType?? default(int); }
      set { _fromTileType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromTileTypeSpecified
    {
      get { return this._fromTileType != null; }
      set { if (value == (this._fromTileType== null)) this._fromTileType = value ? this.fromTileType : (int?)null; }
    }
    private bool ShouldSerializefromTileType() { return fromTileTypeSpecified; }
    private void ResetfromTileType() { fromTileTypeSpecified = false; }
    
    private int? _toserverid;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"toserverid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toserverid
    {
      get { return _toserverid?? default(int); }
      set { _toserverid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toserveridSpecified
    {
      get { return this._toserverid != null; }
      set { if (value == (this._toserverid== null)) this._toserverid = value ? this.toserverid : (int?)null; }
    }
    private bool ShouldSerializetoserverid() { return toserveridSpecified; }
    private void Resettoserverid() { toserveridSpecified = false; }
    
    private int? _toPlayerId;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"toPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toPlayerId
    {
      get { return _toPlayerId?? default(int); }
      set { _toPlayerId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toPlayerIdSpecified
    {
      get { return this._toPlayerId != null; }
      set { if (value == (this._toPlayerId== null)) this._toPlayerId = value ? this.toPlayerId : (int?)null; }
    }
    private bool ShouldSerializetoPlayerId() { return toPlayerIdSpecified; }
    private void ResettoPlayerId() { toPlayerIdSpecified = false; }
    
    private string _toPlayerName;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"toPlayerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string toPlayerName
    {
      get { return _toPlayerName?? ""; }
      set { _toPlayerName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toPlayerNameSpecified
    {
      get { return this._toPlayerName != null; }
      set { if (value == (this._toPlayerName== null)) this._toPlayerName = value ? this.toPlayerName : (string)null; }
    }
    private bool ShouldSerializetoPlayerName() { return toPlayerNameSpecified; }
    private void ResettoPlayerName() { toPlayerNameSpecified = false; }
    
    private int? _toTileId;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"toTileId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toTileId
    {
      get { return _toTileId?? default(int); }
      set { _toTileId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toTileIdSpecified
    {
      get { return this._toTileId != null; }
      set { if (value == (this._toTileId== null)) this._toTileId = value ? this.toTileId : (int?)null; }
    }
    private bool ShouldSerializetoTileId() { return toTileIdSpecified; }
    private void ResettoTileId() { toTileIdSpecified = false; }
    
    private int? _toTileType;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"toTileType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toTileType
    {
      get { return _toTileType?? default(int); }
      set { _toTileType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toTileTypeSpecified
    {
      get { return this._toTileType != null; }
      set { if (value == (this._toTileType== null)) this._toTileType = value ? this.toTileType : (int?)null; }
    }
    private bool ShouldSerializetoTileType() { return toTileTypeSpecified; }
    private void ResettoTileType() { toTileTypeSpecified = false; }
    
    private int? _toAllianceId;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"toAllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toAllianceId
    {
      get { return _toAllianceId?? default(int); }
      set { _toAllianceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toAllianceIdSpecified
    {
      get { return this._toAllianceId != null; }
      set { if (value == (this._toAllianceId== null)) this._toAllianceId = value ? this.toAllianceId : (int?)null; }
    }
    private bool ShouldSerializetoAllianceId() { return toAllianceIdSpecified; }
    private void ResettoAllianceId() { toAllianceIdSpecified = false; }
    
    private int? _toXCoord;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"toXCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toXCoord
    {
      get { return _toXCoord?? default(int); }
      set { _toXCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toXCoordSpecified
    {
      get { return this._toXCoord != null; }
      set { if (value == (this._toXCoord== null)) this._toXCoord = value ? this.toXCoord : (int?)null; }
    }
    private bool ShouldSerializetoXCoord() { return toXCoordSpecified; }
    private void ResettoXCoord() { toXCoordSpecified = false; }
    
    private int? _toYCoord;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"toYCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toYCoord
    {
      get { return _toYCoord?? default(int); }
      set { _toYCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toYCoordSpecified
    {
      get { return this._toYCoord != null; }
      set { if (value == (this._toYCoord== null)) this._toYCoord = value ? this.toYCoord : (int?)null; }
    }
    private bool ShouldSerializetoYCoord() { return toYCoordSpecified; }
    private void ResettoYCoord() { toYCoordSpecified = false; }
    
    private int? _marchType;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"marchType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchType
    {
      get { return _marchType?? default(int); }
      set { _marchType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool marchTypeSpecified
    {
      get { return this._marchType != null; }
      set { if (value == (this._marchType== null)) this._marchType = value ? this.marchType : (int?)null; }
    }
    private bool ShouldSerializemarchType() { return marchTypeSpecified; }
    private void ResetmarchType() { marchTypeSpecified = false; }
    
    private int? _marchStatus;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"marchStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchStatus
    {
      get { return _marchStatus?? default(int); }
      set { _marchStatus = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool marchStatusSpecified
    {
      get { return this._marchStatus != null; }
      set { if (value == (this._marchStatus== null)) this._marchStatus = value ? this.marchStatus : (int?)null; }
    }
    private bool ShouldSerializemarchStatus() { return marchStatusSpecified; }
    private void ResetmarchStatus() { marchStatusSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<PBMsgAVAMarchList.Unit> _unitlist = new global::System.Collections.Generic.List<PBMsgAVAMarchList.Unit>();
    [global::ProtoBuf.ProtoMember(21, Name=@"unitlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAVAMarchList.Unit> unitlist
    {
      get { return _unitlist; }
    }
  
    private readonly global::System.Collections.Generic.List<PBMsgAVAMarchList.Unit> _returnunit = new global::System.Collections.Generic.List<PBMsgAVAMarchList.Unit>();
    [global::ProtoBuf.ProtoMember(22, Name=@"returnunit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAVAMarchList.Unit> returnunit
    {
      get { return _returnunit; }
    }
  
    private readonly global::System.Collections.Generic.List<PBMsgAVAMarchList.HeroInfo> _herolist = new global::System.Collections.Generic.List<PBMsgAVAMarchList.HeroInfo>();
    [global::ProtoBuf.ProtoMember(23, Name=@"herolist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAVAMarchList.HeroInfo> herolist
    {
      get { return _herolist; }
    }
  
    private int? _marchTimestamp;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"marchTimestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchTimestamp
    {
      get { return _marchTimestamp?? default(int); }
      set { _marchTimestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool marchTimestampSpecified
    {
      get { return this._marchTimestamp != null; }
      set { if (value == (this._marchTimestamp== null)) this._marchTimestamp = value ? this.marchTimestamp : (int?)null; }
    }
    private bool ShouldSerializemarchTimestamp() { return marchTimestampSpecified; }
    private void ResetmarchTimestamp() { marchTimestampSpecified = false; }
    
    private int? _destinationEta;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"destinationEta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int destinationEta
    {
      get { return _destinationEta?? default(int); }
      set { _destinationEta = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool destinationEtaSpecified
    {
      get { return this._destinationEta != null; }
      set { if (value == (this._destinationEta== null)) this._destinationEta = value ? this.destinationEta : (int?)null; }
    }
    private bool ShouldSerializedestinationEta() { return destinationEtaSpecified; }
    private void ResetdestinationEta() { destinationEtaSpecified = false; }
    
    private int? _returnEta;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"returnEta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int returnEta
    {
      get { return _returnEta?? default(int); }
      set { _returnEta = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool returnEtaSpecified
    {
      get { return this._returnEta != null; }
      set { if (value == (this._returnEta== null)) this._returnEta = value ? this.returnEta : (int?)null; }
    }
    private bool ShouldSerializereturnEta() { return returnEtaSpecified; }
    private void ResetreturnEta() { returnEtaSpecified = false; }
    
    private int? _speed;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int speed
    {
      get { return _speed?? default(int); }
      set { _speed = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool speedSpecified
    {
      get { return this._speed != null; }
      set { if (value == (this._speed== null)) this._speed = value ? this.speed : (int?)null; }
    }
    private bool ShouldSerializespeed() { return speedSpecified; }
    private void Resetspeed() { speedSpecified = false; }
    
    private int? _knightId;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"knightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int knightId
    {
      get { return _knightId?? default(int); }
      set { _knightId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightIdSpecified
    {
      get { return this._knightId != null; }
      set { if (value == (this._knightId== null)) this._knightId = value ? this.knightId : (int?)null; }
    }
    private bool ShouldSerializeknightId() { return knightIdSpecified; }
    private void ResetknightId() { knightIdSpecified = false; }
    
    private int? _cityOrder;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"cityOrder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cityOrder
    {
      get { return _cityOrder?? default(int); }
      set { _cityOrder = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cityOrderSpecified
    {
      get { return this._cityOrder != null; }
      set { if (value == (this._cityOrder== null)) this._cityOrder = value ? this.cityOrder : (int?)null; }
    }
    private bool ShouldSerializecityOrder() { return cityOrderSpecified; }
    private void ResetcityOrder() { cityOrderSpecified = false; }
    
    private string _knightName;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"knightName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string knightName
    {
      get { return _knightName?? ""; }
      set { _knightName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightNameSpecified
    {
      get { return this._knightName != null; }
      set { if (value == (this._knightName== null)) this._knightName = value ? this.knightName : (string)null; }
    }
    private bool ShouldSerializeknightName() { return knightNameSpecified; }
    private void ResetknightName() { knightNameSpecified = false; }
    
    private int? _knightLevel;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"knightLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int knightLevel
    {
      get { return _knightLevel?? default(int); }
      set { _knightLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightLevelSpecified
    {
      get { return this._knightLevel != null; }
      set { if (value == (this._knightLevel== null)) this._knightLevel = value ? this.knightLevel : (int?)null; }
    }
    private bool ShouldSerializeknightLevel() { return knightLevelSpecified; }
    private void ResetknightLevel() { knightLevelSpecified = false; }
    
    private int? _oneWaySecond;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"oneWaySecond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int oneWaySecond
    {
      get { return _oneWaySecond?? default(int); }
      set { _oneWaySecond = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool oneWaySecondSpecified
    {
      get { return this._oneWaySecond != null; }
      set { if (value == (this._oneWaySecond== null)) this._oneWaySecond = value ? this.oneWaySecond : (int?)null; }
    }
    private bool ShouldSerializeoneWaySecond() { return oneWaySecondSpecified; }
    private void ResetoneWaySecond() { oneWaySecondSpecified = false; }
    
    private int? _isWin;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"isWin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isWin
    {
      get { return _isWin?? default(int); }
      set { _isWin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool isWinSpecified
    {
      get { return this._isWin != null; }
      set { if (value == (this._isWin== null)) this._isWin = value ? this.isWin : (int?)null; }
    }
    private bool ShouldSerializeisWin() { return isWinSpecified; }
    private void ResetisWin() { isWinSpecified = false; }
    
    private PBMsgAVAMarchList.RallyAttackInfo _rallyAttackInfo = null;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"rallyAttackInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgAVAMarchList.RallyAttackInfo rallyAttackInfo
    {
      get { return _rallyAttackInfo; }
      set { _rallyAttackInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}