//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgReqAVALeagueLeaderboard.proto
namespace PBMsgReqAVALeagueLeaderboard
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgReqAVALeagueLeaderboard")]
  public partial class PBMsgReqAVALeagueLeaderboard : global::ProtoBuf.IExtensible
  {
    public PBMsgReqAVALeagueLeaderboard() {}
    
    private int? _act;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"act", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int act
    {
      get { return _act?? default(int); }
      set { _act = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool actSpecified
    {
      get { return this._act != null; }
      set { if (value == (this._act== null)) this._act = value ? this.act : (int?)null; }
    }
    private bool ShouldSerializeact() { return actSpecified; }
    private void Resetact() { actSpecified = false; }
    
    private int? _pageNo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pageNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pageNo
    {
      get { return _pageNo?? default(int); }
      set { _pageNo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pageNoSpecified
    {
      get { return this._pageNo != null; }
      set { if (value == (this._pageNo== null)) this._pageNo = value ? this.pageNo : (int?)null; }
    }
    private bool ShouldSerializepageNo() { return pageNoSpecified; }
    private void ResetpageNo() { pageNoSpecified = false; }
    
    private int? _leagueNo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"leagueNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leagueNo
    {
      get { return _leagueNo?? default(int); }
      set { _leagueNo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool leagueNoSpecified
    {
      get { return this._leagueNo != null; }
      set { if (value == (this._leagueNo== null)) this._leagueNo = value ? this.leagueNo : (int?)null; }
    }
    private bool ShouldSerializeleagueNo() { return leagueNoSpecified; }
    private void ResetleagueNo() { leagueNoSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}