//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAVAEvent.proto
namespace PBMsgAVAEvent
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAVAEvent")]
  public partial class PBMsgAVAEvent : global::ProtoBuf.IExtensible
  {
    public PBMsgAVAEvent() {}
    
    private int? _actId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"actId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int actId
    {
      get { return _actId?? default(int); }
      set { _actId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool actIdSpecified
    {
      get { return this._actId != null; }
      set { if (value == (this._actId== null)) this._actId = value ? this.actId : (int?)null; }
    }
    private bool ShouldSerializeactId() { return actIdSpecified; }
    private void ResetactId() { actIdSpecified = false; }
    
    private long? _prepareTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"prepareTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long prepareTime
    {
      get { return _prepareTime?? default(long); }
      set { _prepareTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool prepareTimeSpecified
    {
      get { return this._prepareTime != null; }
      set { if (value == (this._prepareTime== null)) this._prepareTime = value ? this.prepareTime : (long?)null; }
    }
    private bool ShouldSerializeprepareTime() { return prepareTimeSpecified; }
    private void ResetprepareTime() { prepareTimeSpecified = false; }
    
    private long? _matchTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"matchTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long matchTime
    {
      get { return _matchTime?? default(long); }
      set { _matchTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool matchTimeSpecified
    {
      get { return this._matchTime != null; }
      set { if (value == (this._matchTime== null)) this._matchTime = value ? this.matchTime : (long?)null; }
    }
    private bool ShouldSerializematchTime() { return matchTimeSpecified; }
    private void ResetmatchTime() { matchTimeSpecified = false; }
    
    private long? _frozenTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"frozenTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long frozenTime
    {
      get { return _frozenTime?? default(long); }
      set { _frozenTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool frozenTimeSpecified
    {
      get { return this._frozenTime != null; }
      set { if (value == (this._frozenTime== null)) this._frozenTime = value ? this.frozenTime : (long?)null; }
    }
    private bool ShouldSerializefrozenTime() { return frozenTimeSpecified; }
    private void ResetfrozenTime() { frozenTimeSpecified = false; }
    
    private long? _startTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long startTime
    {
      get { return _startTime?? default(long); }
      set { _startTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool startTimeSpecified
    {
      get { return this._startTime != null; }
      set { if (value == (this._startTime== null)) this._startTime = value ? this.startTime : (long?)null; }
    }
    private bool ShouldSerializestartTime() { return startTimeSpecified; }
    private void ResetstartTime() { startTimeSpecified = false; }
    
    private long? _endTime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long endTime
    {
      get { return _endTime?? default(long); }
      set { _endTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool endTimeSpecified
    {
      get { return this._endTime != null; }
      set { if (value == (this._endTime== null)) this._endTime = value ? this.endTime : (long?)null; }
    }
    private bool ShouldSerializeendTime() { return endTimeSpecified; }
    private void ResetendTime() { endTimeSpecified = false; }
    
    private long? _rewardTime;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rewardTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long rewardTime
    {
      get { return _rewardTime?? default(long); }
      set { _rewardTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rewardTimeSpecified
    {
      get { return this._rewardTime != null; }
      set { if (value == (this._rewardTime== null)) this._rewardTime = value ? this.rewardTime : (long?)null; }
    }
    private bool ShouldSerializerewardTime() { return rewardTimeSpecified; }
    private void ResetrewardTime() { rewardTimeSpecified = false; }
    
    private string _description;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string description
    {
      get { return _description?? ""; }
      set { _description = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool descriptionSpecified
    {
      get { return this._description != null; }
      set { if (value == (this._description== null)) this._description = value ? this.description : (string)null; }
    }
    private bool ShouldSerializedescription() { return descriptionSpecified; }
    private void Resetdescription() { descriptionSpecified = false; }
    
    private string _state;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string state
    {
      get { return _state?? ""; }
      set { _state = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stateSpecified
    {
      get { return this._state != null; }
      set { if (value == (this._state== null)) this._state = value ? this.state : (string)null; }
    }
    private bool ShouldSerializestate() { return stateSpecified; }
    private void Resetstate() { stateSpecified = false; }
    
    private long? _superWonderProtectTime;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"superWonderProtectTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long superWonderProtectTime
    {
      get { return _superWonderProtectTime?? default(long); }
      set { _superWonderProtectTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool superWonderProtectTimeSpecified
    {
      get { return this._superWonderProtectTime != null; }
      set { if (value == (this._superWonderProtectTime== null)) this._superWonderProtectTime = value ? this.superWonderProtectTime : (long?)null; }
    }
    private bool ShouldSerializesuperWonderProtectTime() { return superWonderProtectTimeSpecified; }
    private void ResetsuperWonderProtectTime() { superWonderProtectTimeSpecified = false; }
    
    private long? _startTimeEUUnix;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"startTimeEUUnix", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long startTimeEUUnix
    {
      get { return _startTimeEUUnix?? default(long); }
      set { _startTimeEUUnix = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool startTimeEUUnixSpecified
    {
      get { return this._startTimeEUUnix != null; }
      set { if (value == (this._startTimeEUUnix== null)) this._startTimeEUUnix = value ? this.startTimeEUUnix : (long?)null; }
    }
    private bool ShouldSerializestartTimeEUUnix() { return startTimeEUUnixSpecified; }
    private void ResetstartTimeEUUnix() { startTimeEUUnixSpecified = false; }
    
    private long? _startTimeNAUnix;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"startTimeNAUnix", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long startTimeNAUnix
    {
      get { return _startTimeNAUnix?? default(long); }
      set { _startTimeNAUnix = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool startTimeNAUnixSpecified
    {
      get { return this._startTimeNAUnix != null; }
      set { if (value == (this._startTimeNAUnix== null)) this._startTimeNAUnix = value ? this.startTimeNAUnix : (long?)null; }
    }
    private bool ShouldSerializestartTimeNAUnix() { return startTimeNAUnixSpecified; }
    private void ResetstartTimeNAUnix() { startTimeNAUnixSpecified = false; }
    
    private int? _isFinished;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"isFinished", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isFinished
    {
      get { return _isFinished?? default(int); }
      set { _isFinished = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool isFinishedSpecified
    {
      get { return this._isFinished != null; }
      set { if (value == (this._isFinished== null)) this._isFinished = value ? this.isFinished : (int?)null; }
    }
    private bool ShouldSerializeisFinished() { return isFinishedSpecified; }
    private void ResetisFinished() { isFinishedSpecified = false; }
    
    private long? _endTimeEUUnix;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"endTimeEUUnix", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long endTimeEUUnix
    {
      get { return _endTimeEUUnix?? default(long); }
      set { _endTimeEUUnix = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool endTimeEUUnixSpecified
    {
      get { return this._endTimeEUUnix != null; }
      set { if (value == (this._endTimeEUUnix== null)) this._endTimeEUUnix = value ? this.endTimeEUUnix : (long?)null; }
    }
    private bool ShouldSerializeendTimeEUUnix() { return endTimeEUUnixSpecified; }
    private void ResetendTimeEUUnix() { endTimeEUUnixSpecified = false; }
    
    private long? _endTimeNAUnix;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"endTimeNAUnix", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long endTimeNAUnix
    {
      get { return _endTimeNAUnix?? default(long); }
      set { _endTimeNAUnix = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool endTimeNAUnixSpecified
    {
      get { return this._endTimeNAUnix != null; }
      set { if (value == (this._endTimeNAUnix== null)) this._endTimeNAUnix = value ? this.endTimeNAUnix : (long?)null; }
    }
    private bool ShouldSerializeendTimeNAUnix() { return endTimeNAUnixSpecified; }
    private void ResetendTimeNAUnix() { endTimeNAUnixSpecified = false; }
    
    private string _allianceRegion;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"allianceRegion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string allianceRegion
    {
      get { return _allianceRegion?? ""; }
      set { _allianceRegion = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool allianceRegionSpecified
    {
      get { return this._allianceRegion != null; }
      set { if (value == (this._allianceRegion== null)) this._allianceRegion = value ? this.allianceRegion : (string)null; }
    }
    private bool ShouldSerializeallianceRegion() { return allianceRegionSpecified; }
    private void ResetallianceRegion() { allianceRegionSpecified = false; }
    
    private string _mode;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mode
    {
      get { return _mode?? ""; }
      set { _mode = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool modeSpecified
    {
      get { return this._mode != null; }
      set { if (value == (this._mode== null)) this._mode = value ? this.mode : (string)null; }
    }
    private bool ShouldSerializemode() { return modeSpecified; }
    private void Resetmode() { modeSpecified = false; }
    
    private string _isApply;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"isApply", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string isApply
    {
      get { return _isApply?? ""; }
      set { _isApply = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool isApplySpecified
    {
      get { return this._isApply != null; }
      set { if (value == (this._isApply== null)) this._isApply = value ? this.isApply : (string)null; }
    }
    private bool ShouldSerializeisApply() { return isApplySpecified; }
    private void ResetisApply() { isApplySpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}