//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAllianceDonate.proto
namespace PBMsgAllianceDonate
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAllianceDonate")]
  public partial class PBMsgAllianceDonate : global::ProtoBuf.IExtensible
  {
    public PBMsgAllianceDonate() {}
    
    private int? _stoneAp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stoneAp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stoneAp
    {
      get { return _stoneAp?? default(int); }
      set { _stoneAp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stoneApSpecified
    {
      get { return this._stoneAp != null; }
      set { if (value == (this._stoneAp== null)) this._stoneAp = value ? this.stoneAp : (int?)null; }
    }
    private bool ShouldSerializestoneAp() { return stoneApSpecified; }
    private void ResetstoneAp() { stoneApSpecified = false; }
    
    private int? _oreAp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"oreAp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int oreAp
    {
      get { return _oreAp?? default(int); }
      set { _oreAp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool oreApSpecified
    {
      get { return this._oreAp != null; }
      set { if (value == (this._oreAp== null)) this._oreAp = value ? this.oreAp : (int?)null; }
    }
    private bool ShouldSerializeoreAp() { return oreApSpecified; }
    private void ResetoreAp() { oreApSpecified = false; }
    
    private int? _woodAp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"woodAp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int woodAp
    {
      get { return _woodAp?? default(int); }
      set { _woodAp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool woodApSpecified
    {
      get { return this._woodAp != null; }
      set { if (value == (this._woodAp== null)) this._woodAp = value ? this.woodAp : (int?)null; }
    }
    private bool ShouldSerializewoodAp() { return woodApSpecified; }
    private void ResetwoodAp() { woodApSpecified = false; }
    
    private int? _foodAp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"foodAp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int foodAp
    {
      get { return _foodAp?? default(int); }
      set { _foodAp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool foodApSpecified
    {
      get { return this._foodAp != null; }
      set { if (value == (this._foodAp== null)) this._foodAp = value ? this.foodAp : (int?)null; }
    }
    private bool ShouldSerializefoodAp() { return foodApSpecified; }
    private void ResetfoodAp() { foodApSpecified = false; }
    
    private int? _goldAp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"goldAp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goldAp
    {
      get { return _goldAp?? default(int); }
      set { _goldAp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goldApSpecified
    {
      get { return this._goldAp != null; }
      set { if (value == (this._goldAp== null)) this._goldAp = value ? this.goldAp : (int?)null; }
    }
    private bool ShouldSerializegoldAp() { return goldApSpecified; }
    private void ResetgoldAp() { goldApSpecified = false; }
    
    private int? _itemAp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"itemAp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemAp
    {
      get { return _itemAp?? default(int); }
      set { _itemAp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemApSpecified
    {
      get { return this._itemAp != null; }
      set { if (value == (this._itemAp== null)) this._itemAp = value ? this.itemAp : (int?)null; }
    }
    private bool ShouldSerializeitemAp() { return itemApSpecified; }
    private void ResetitemAp() { itemApSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private long? _cap;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"cap", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long cap
    {
      get { return _cap?? default(long); }
      set { _cap = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool capSpecified
    {
      get { return this._cap != null; }
      set { if (value == (this._cap== null)) this._cap = value ? this.cap : (long?)null; }
    }
    private bool ShouldSerializecap() { return capSpecified; }
    private void Resetcap() { capSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}