//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAVASeed.proto
namespace PBMsgAVASeed
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAVASeed")]
  public partial class PBMsgAVASeed : global::ProtoBuf.IExtensible
  {
    public PBMsgAVASeed() {}
    
    private PBMsgAVASeed.RallyPoint _rallyPoint = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rallyPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgAVASeed.RallyPoint rallyPoint
    {
      get { return _rallyPoint; }
      set { _rallyPoint = value; }
    }
    private PBMsgAVASeed.AllianceRally _allianceRally = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"allianceRally", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgAVASeed.AllianceRally allianceRally
    {
      get { return _allianceRally; }
      set { _allianceRally = value; }
    }
    private PBMsgAVASeed.EagleEye _eagleEye = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"eagleEye", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgAVASeed.EagleEye eagleEye
    {
      get { return _eagleEye; }
      set { _eagleEye = value; }
    }
    private PBMsgAVASeed.Embassy _embassy = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"embassy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgAVASeed.Embassy embassy
    {
      get { return _embassy; }
      set { _embassy = value; }
    }
    private PBMsgAVASeed.WatchTower _watchTower = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"watchTower", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgAVASeed.WatchTower watchTower
    {
      get { return _watchTower; }
      set { _watchTower = value; }
    }
    private int? _tileId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"tileId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileId
    {
      get { return _tileId?? default(int); }
      set { _tileId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileIdSpecified
    {
      get { return this._tileId != null; }
      set { if (value == (this._tileId== null)) this._tileId = value ? this.tileId : (int?)null; }
    }
    private bool ShouldSerializetileId() { return tileIdSpecified; }
    private void ResettileId() { tileIdSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<PBMsgAVASeed.Item> _items = new global::System.Collections.Generic.List<PBMsgAVASeed.Item>();
    [global::ProtoBuf.ProtoMember(7, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAVASeed.Item> items
    {
      get { return _items; }
    }
  
    private int? _defenseKnight;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"defenseKnight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defenseKnight
    {
      get { return _defenseKnight?? default(int); }
      set { _defenseKnight = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool defenseKnightSpecified
    {
      get { return this._defenseKnight != null; }
      set { if (value == (this._defenseKnight== null)) this._defenseKnight = value ? this.defenseKnight : (int?)null; }
    }
    private bool ShouldSerializedefenseKnight() { return defenseKnightSpecified; }
    private void ResetdefenseKnight() { defenseKnightSpecified = false; }
    
    private int? _rallyDetailDisplayLimit;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"rallyDetailDisplayLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rallyDetailDisplayLimit
    {
      get { return _rallyDetailDisplayLimit?? default(int); }
      set { _rallyDetailDisplayLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rallyDetailDisplayLimitSpecified
    {
      get { return this._rallyDetailDisplayLimit != null; }
      set { if (value == (this._rallyDetailDisplayLimit== null)) this._rallyDetailDisplayLimit = value ? this.rallyDetailDisplayLimit : (int?)null; }
    }
    private bool ShouldSerializerallyDetailDisplayLimit() { return rallyDetailDisplayLimitSpecified; }
    private void ResetrallyDetailDisplayLimit() { rallyDetailDisplayLimitSpecified = false; }
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _allianceId;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"allianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int allianceId
    {
      get { return _allianceId; }
      set { _allianceId = value; }
    }
    private PBMsgAVASeed.Emblem _enemyEmblemInfo = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"enemyEmblemInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgAVASeed.Emblem enemyEmblemInfo
    {
      get { return _enemyEmblemInfo; }
      set { _enemyEmblemInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _allianceScores = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(13, Name=@"allianceScores", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> allianceScores
    {
      get { return _allianceScores; }
    }
  
    private PBMsgAVASeed.MatchMakingResult _matchMakingResult = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"matchMakingResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgAVASeed.MatchMakingResult matchMakingResult
    {
      get { return _matchMakingResult; }
      set { _matchMakingResult = value; }
    }
    private string _enemyAllianceName;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"enemyAllianceName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string enemyAllianceName
    {
      get { return _enemyAllianceName?? ""; }
      set { _enemyAllianceName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool enemyAllianceNameSpecified
    {
      get { return this._enemyAllianceName != null; }
      set { if (value == (this._enemyAllianceName== null)) this._enemyAllianceName = value ? this.enemyAllianceName : (string)null; }
    }
    private bool ShouldSerializeenemyAllianceName() { return enemyAllianceNameSpecified; }
    private void ResetenemyAllianceName() { enemyAllianceNameSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<string> _scoreIncRate = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(16, Name=@"scoreIncRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> scoreIncRate
    {
      get { return _scoreIncRate; }
    }
  
    private PBMsgAVASeed.WonderCount _wonderCount = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"wonderCount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgAVASeed.WonderCount wonderCount
    {
      get { return _wonderCount; }
      set { _wonderCount = value; }
    }
    private PBMsgAVASeed.WonderCount _enemyWonderCount = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"enemyWonderCount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgAVASeed.WonderCount enemyWonderCount
    {
      get { return _enemyWonderCount; }
      set { _enemyWonderCount = value; }
    }
    private int? _occupyTileLimit;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"occupyTileLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int occupyTileLimit
    {
      get { return _occupyTileLimit?? default(int); }
      set { _occupyTileLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupyTileLimitSpecified
    {
      get { return this._occupyTileLimit != null; }
      set { if (value == (this._occupyTileLimit== null)) this._occupyTileLimit = value ? this.occupyTileLimit : (int?)null; }
    }
    private bool ShouldSerializeoccupyTileLimit() { return occupyTileLimitSpecified; }
    private void ResetoccupyTileLimit() { occupyTileLimitSpecified = false; }
    
    private int? _myTileCount;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"myTileCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int myTileCount
    {
      get { return _myTileCount?? default(int); }
      set { _myTileCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool myTileCountSpecified
    {
      get { return this._myTileCount != null; }
      set { if (value == (this._myTileCount== null)) this._myTileCount = value ? this.myTileCount : (int?)null; }
    }
    private bool ShouldSerializemyTileCount() { return myTileCountSpecified; }
    private void ResetmyTileCount() { myTileCountSpecified = false; }
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchMakingResult")]
  public partial class MatchMakingResult : global::ProtoBuf.IExtensible
  {
    public MatchMakingResult() {}
    
    private string _myAllianceName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"myAllianceName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string myAllianceName
    {
      get { return _myAllianceName; }
      set { _myAllianceName = value; }
    }
    private long _myAllianceScore;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"myAllianceScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long myAllianceScore
    {
      get { return _myAllianceScore; }
      set { _myAllianceScore = value; }
    }
    private int _myAllianceRank;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"myAllianceRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int myAllianceRank
    {
      get { return _myAllianceRank; }
      set { _myAllianceRank = value; }
    }
    private string _enemyAllianceName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"enemyAllianceName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string enemyAllianceName
    {
      get { return _enemyAllianceName; }
      set { _enemyAllianceName = value; }
    }
    private long _enemyAllianceScore;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"enemyAllianceScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long enemyAllianceScore
    {
      get { return _enemyAllianceScore; }
      set { _enemyAllianceScore = value; }
    }
    private int _enemyAllianceRank;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"enemyAllianceRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int enemyAllianceRank
    {
      get { return _enemyAllianceRank; }
      set { _enemyAllianceRank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllianceRally")]
  public partial class AllianceRally : global::ProtoBuf.IExtensible
  {
    public AllianceRally() {}
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private int? _rallyLimit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rallyLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rallyLimit
    {
      get { return _rallyLimit?? default(int); }
      set { _rallyLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rallyLimitSpecified
    {
      get { return this._rallyLimit != null; }
      set { if (value == (this._rallyLimit== null)) this._rallyLimit = value ? this.rallyLimit : (int?)null; }
    }
    private bool ShouldSerializerallyLimit() { return rallyLimitSpecified; }
    private void ResetrallyLimit() { rallyLimitSpecified = false; }
    
    private int? _troopLimit;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"troopLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int troopLimit
    {
      get { return _troopLimit?? default(int); }
      set { _troopLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool troopLimitSpecified
    {
      get { return this._troopLimit != null; }
      set { if (value == (this._troopLimit== null)) this._troopLimit = value ? this.troopLimit : (int?)null; }
    }
    private bool ShouldSerializetroopLimit() { return troopLimitSpecified; }
    private void ResettroopLimit() { troopLimitSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RallyPoint")]
  public partial class RallyPoint : global::ProtoBuf.IExtensible
  {
    public RallyPoint() {}
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private int? _marchLimit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"marchLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchLimit
    {
      get { return _marchLimit?? default(int); }
      set { _marchLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool marchLimitSpecified
    {
      get { return this._marchLimit != null; }
      set { if (value == (this._marchLimit== null)) this._marchLimit = value ? this.marchLimit : (int?)null; }
    }
    private bool ShouldSerializemarchLimit() { return marchLimitSpecified; }
    private void ResetmarchLimit() { marchLimitSpecified = false; }
    
    private int? _troopLimit;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"troopLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int troopLimit
    {
      get { return _troopLimit?? default(int); }
      set { _troopLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool troopLimitSpecified
    {
      get { return this._troopLimit != null; }
      set { if (value == (this._troopLimit== null)) this._troopLimit = value ? this.troopLimit : (int?)null; }
    }
    private bool ShouldSerializetroopLimit() { return troopLimitSpecified; }
    private void ResettroopLimit() { troopLimitSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private int? _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId?? default(int); }
      set { _itemId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemIdSpecified
    {
      get { return this._itemId != null; }
      set { if (value == (this._itemId== null)) this._itemId = value ? this.itemId : (int?)null; }
    }
    private bool ShouldSerializeitemId() { return itemIdSpecified; }
    private void ResetitemId() { itemIdSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EagleEye")]
  public partial class EagleEye : global::ProtoBuf.IExtensible
  {
    public EagleEye() {}
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Embassy")]
  public partial class Embassy : global::ProtoBuf.IExtensible
  {
    public Embassy() {}
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WatchTower")]
  public partial class WatchTower : global::ProtoBuf.IExtensible
  {
    public WatchTower() {}
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private bool? _canSeeEnemyResearch;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"canSeeEnemyResearch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool canSeeEnemyResearch
    {
      get { return _canSeeEnemyResearch?? default(bool); }
      set { _canSeeEnemyResearch = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool canSeeEnemyResearchSpecified
    {
      get { return this._canSeeEnemyResearch != null; }
      set { if (value == (this._canSeeEnemyResearch== null)) this._canSeeEnemyResearch = value ? this.canSeeEnemyResearch : (bool?)null; }
    }
    private bool ShouldSerializecanSeeEnemyResearch() { return canSeeEnemyResearchSpecified; }
    private void ResetcanSeeEnemyResearch() { canSeeEnemyResearchSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Emblem")]
  public partial class Emblem : global::ProtoBuf.IExtensible
  {
    public Emblem() {}
    
    private string _curBanner;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"curBanner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string curBanner
    {
      get { return _curBanner?? ""; }
      set { _curBanner = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curBannerSpecified
    {
      get { return this._curBanner != null; }
      set { if (value == (this._curBanner== null)) this._curBanner = value ? this.curBanner : (string)null; }
    }
    private bool ShouldSerializecurBanner() { return curBannerSpecified; }
    private void ResetcurBanner() { curBannerSpecified = false; }
    
    private int? _curStyle;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"curStyle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int curStyle
    {
      get { return _curStyle?? default(int); }
      set { _curStyle = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curStyleSpecified
    {
      get { return this._curStyle != null; }
      set { if (value == (this._curStyle== null)) this._curStyle = value ? this.curStyle : (int?)null; }
    }
    private bool ShouldSerializecurStyle() { return curStyleSpecified; }
    private void ResetcurStyle() { curStyleSpecified = false; }
    
    private string _curStyleColor;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"curStyleColor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string curStyleColor
    {
      get { return _curStyleColor?? ""; }
      set { _curStyleColor = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curStyleColorSpecified
    {
      get { return this._curStyleColor != null; }
      set { if (value == (this._curStyleColor== null)) this._curStyleColor = value ? this.curStyleColor : (string)null; }
    }
    private bool ShouldSerializecurStyleColor() { return curStyleColorSpecified; }
    private void ResetcurStyleColor() { curStyleColorSpecified = false; }
    
    private int? _curSymbol;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"curSymbol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int curSymbol
    {
      get { return _curSymbol?? default(int); }
      set { _curSymbol = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curSymbolSpecified
    {
      get { return this._curSymbol != null; }
      set { if (value == (this._curSymbol== null)) this._curSymbol = value ? this.curSymbol : (int?)null; }
    }
    private bool ShouldSerializecurSymbol() { return curSymbolSpecified; }
    private void ResetcurSymbol() { curSymbolSpecified = false; }
    
    private string _curSymbolColor;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"curSymbolColor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string curSymbolColor
    {
      get { return _curSymbolColor?? ""; }
      set { _curSymbolColor = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curSymbolColorSpecified
    {
      get { return this._curSymbolColor != null; }
      set { if (value == (this._curSymbolColor== null)) this._curSymbolColor = value ? this.curSymbolColor : (string)null; }
    }
    private bool ShouldSerializecurSymbolColor() { return curSymbolColorSpecified; }
    private void ResetcurSymbolColor() { curSymbolColorSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WonderCount")]
  public partial class WonderCount : global::ProtoBuf.IExtensible
  {
    public WonderCount() {}
    
    private int? _superWonder;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"superWonder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int superWonder
    {
      get { return _superWonder?? default(int); }
      set { _superWonder = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool superWonderSpecified
    {
      get { return this._superWonder != null; }
      set { if (value == (this._superWonder== null)) this._superWonder = value ? this.superWonder : (int?)null; }
    }
    private bool ShouldSerializesuperWonder() { return superWonderSpecified; }
    private void ResetsuperWonder() { superWonderSpecified = false; }
    
    private int? _wonder;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"wonder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wonder
    {
      get { return _wonder?? default(int); }
      set { _wonder = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool wonderSpecified
    {
      get { return this._wonder != null; }
      set { if (value == (this._wonder== null)) this._wonder = value ? this.wonder : (int?)null; }
    }
    private bool ShouldSerializewonder() { return wonderSpecified; }
    private void Resetwonder() { wonderSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}