//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAllianceSkillInfo.proto
namespace PBMsgAllianceSkillInfo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAllianceSkillInfo")]
  public partial class PBMsgAllianceSkillInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgAllianceSkillInfo() {}
    
    private readonly global::System.Collections.Generic.List<PBMsgAllianceSkillInfo.skillEntry> _skillList = new global::System.Collections.Generic.List<PBMsgAllianceSkillInfo.skillEntry>();
    [global::ProtoBuf.ProtoMember(1, Name=@"skillList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAllianceSkillInfo.skillEntry> skillList
    {
      get { return _skillList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"skillEntry")]
  public partial class skillEntry : global::ProtoBuf.IExtensible
  {
    public skillEntry() {}
    
    private int _skillId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private int _skillLevel;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillLevel
    {
      get { return _skillLevel; }
      set { _skillLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}