//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgReqAVARelocate.proto
namespace PBMsgReqAVARelocate
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgReqAVARelocate")]
  public partial class PBMsgReqAVARelocate : global::ProtoBuf.IExtensible
  {
    public PBMsgReqAVARelocate() {}
    
    private int _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int? _xCoord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"xCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xCoord
    {
      get { return _xCoord?? default(int); }
      set { _xCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool xCoordSpecified
    {
      get { return this._xCoord != null; }
      set { if (value == (this._xCoord== null)) this._xCoord = value ? this.xCoord : (int?)null; }
    }
    private bool ShouldSerializexCoord() { return xCoordSpecified; }
    private void ResetxCoord() { xCoordSpecified = false; }
    
    private int? _yCoord;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"yCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int yCoord
    {
      get { return _yCoord?? default(int); }
      set { _yCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool yCoordSpecified
    {
      get { return this._yCoord != null; }
      set { if (value == (this._yCoord== null)) this._yCoord = value ? this.yCoord : (int?)null; }
    }
    private bool ShouldSerializeyCoord() { return yCoordSpecified; }
    private void ResetyCoord() { yCoordSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}