//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAvaScoutRes.proto
namespace PBMsgAvaScoutRes
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAvaScoutRes")]
  public partial class PBMsgAvaScoutRes : global::ProtoBuf.IExtensible
  {
    public PBMsgAvaScoutRes() {}
    
    private int? _scoutRemainTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"scoutRemainTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int scoutRemainTime
    {
      get { return _scoutRemainTime?? default(int); }
      set { _scoutRemainTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoutRemainTimeSpecified
    {
      get { return this._scoutRemainTime != null; }
      set { if (value == (this._scoutRemainTime== null)) this._scoutRemainTime = value ? this.scoutRemainTime : (int?)null; }
    }
    private bool ShouldSerializescoutRemainTime() { return scoutRemainTimeSpecified; }
    private void ResetscoutRemainTime() { scoutRemainTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}