//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAvaDeletedSharedTile.proto
namespace PBMsgAvaDeletedSharedTile
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAvaDeletedSharedTile")]
  public partial class PBMsgAvaDeletedSharedTile : global::ProtoBuf.IExtensible
  {
    public PBMsgAvaDeletedSharedTile() {}
    
    private readonly global::System.Collections.Generic.List<int> _deletedTileIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"deletedTileIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> deletedTileIds
    {
      get { return _deletedTileIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}