//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAVAMap.proto
namespace PBMsgAVAMap
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAVAMap")]
  public partial class PBMsgAVAMap : global::ProtoBuf.IExtensible
  {
    public PBMsgAVAMap() {}
    
    private int? _actId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"actId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int actId
    {
      get { return _actId?? default(int); }
      set { _actId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool actIdSpecified
    {
      get { return this._actId != null; }
      set { if (value == (this._actId== null)) this._actId = value ? this.actId : (int?)null; }
    }
    private bool ShouldSerializeactId() { return actIdSpecified; }
    private void ResetactId() { actIdSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<PBMsgAVAMap.Tile> _tile = new global::System.Collections.Generic.List<PBMsgAVAMap.Tile>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgAVAMap.Tile> tile
    {
      get { return _tile; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tile")]
  public partial class Tile : global::ProtoBuf.IExtensible
  {
    public Tile() {}
    
    private int? _xcoord;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"xcoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xcoord
    {
      get { return _xcoord?? default(int); }
      set { _xcoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool xcoordSpecified
    {
      get { return this._xcoord != null; }
      set { if (value == (this._xcoord== null)) this._xcoord = value ? this.xcoord : (int?)null; }
    }
    private bool ShouldSerializexcoord() { return xcoordSpecified; }
    private void Resetxcoord() { xcoordSpecified = false; }
    
    private int? _ycoord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ycoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ycoord
    {
      get { return _ycoord?? default(int); }
      set { _ycoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ycoordSpecified
    {
      get { return this._ycoord != null; }
      set { if (value == (this._ycoord== null)) this._ycoord = value ? this.ycoord : (int?)null; }
    }
    private bool ShouldSerializeycoord() { return ycoordSpecified; }
    private void Resetycoord() { ycoordSpecified = false; }
    
    private int? _tileId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tileId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileId
    {
      get { return _tileId?? default(int); }
      set { _tileId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileIdSpecified
    {
      get { return this._tileId != null; }
      set { if (value == (this._tileId== null)) this._tileId = value ? this.tileId : (int?)null; }
    }
    private bool ShouldSerializetileId() { return tileIdSpecified; }
    private void ResettileId() { tileIdSpecified = false; }
    
    private int? _blockId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"blockId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int blockId
    {
      get { return _blockId?? default(int); }
      set { _blockId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool blockIdSpecified
    {
      get { return this._blockId != null; }
      set { if (value == (this._blockId== null)) this._blockId = value ? this.blockId : (int?)null; }
    }
    private bool ShouldSerializeblockId() { return blockIdSpecified; }
    private void ResetblockId() { blockIdSpecified = false; }
    
    private int? _provinceId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"provinceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int provinceId
    {
      get { return _provinceId?? default(int); }
      set { _provinceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool provinceIdSpecified
    {
      get { return this._provinceId != null; }
      set { if (value == (this._provinceId== null)) this._provinceId = value ? this.provinceId : (int?)null; }
    }
    private bool ShouldSerializeprovinceId() { return provinceIdSpecified; }
    private void ResetprovinceId() { provinceIdSpecified = false; }
    
    private int? _tileType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"tileType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileType
    {
      get { return _tileType?? default(int); }
      set { _tileType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileTypeSpecified
    {
      get { return this._tileType != null; }
      set { if (value == (this._tileType== null)) this._tileType = value ? this.tileType : (int?)null; }
    }
    private bool ShouldSerializetileType() { return tileTypeSpecified; }
    private void ResettileType() { tileTypeSpecified = false; }
    
    private int? _serverId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"serverId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverId
    {
      get { return _serverId?? default(int); }
      set { _serverId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool serverIdSpecified
    {
      get { return this._serverId != null; }
      set { if (value == (this._serverId== null)) this._serverId = value ? this.serverId : (int?)null; }
    }
    private bool ShouldSerializeserverId() { return serverIdSpecified; }
    private void ResetserverId() { serverIdSpecified = false; }
    
    private int? _allianceId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"allianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int allianceId
    {
      get { return _allianceId?? default(int); }
      set { _allianceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool allianceIdSpecified
    {
      get { return this._allianceId != null; }
      set { if (value == (this._allianceId== null)) this._allianceId = value ? this.allianceId : (int?)null; }
    }
    private bool ShouldSerializeallianceId() { return allianceIdSpecified; }
    private void ResetallianceId() { allianceIdSpecified = false; }
    
    private int? _userId;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId?? default(int); }
      set { _userId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool userIdSpecified
    {
      get { return this._userId != null; }
      set { if (value == (this._userId== null)) this._userId = value ? this.userId : (int?)null; }
    }
    private bool ShouldSerializeuserId() { return userIdSpecified; }
    private void ResetuserId() { userIdSpecified = false; }
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName?? ""; }
      set { _userName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool userNameSpecified
    {
      get { return this._userName != null; }
      set { if (value == (this._userName== null)) this._userName = value ? this.userName : (string)null; }
    }
    private bool ShouldSerializeuserName() { return userNameSpecified; }
    private void ResetuserName() { userNameSpecified = false; }
    
    private string _allianceName;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"allianceName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string allianceName
    {
      get { return _allianceName?? ""; }
      set { _allianceName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool allianceNameSpecified
    {
      get { return this._allianceName != null; }
      set { if (value == (this._allianceName== null)) this._allianceName = value ? this.allianceName : (string)null; }
    }
    private bool ShouldSerializeallianceName() { return allianceNameSpecified; }
    private void ResetallianceName() { allianceNameSpecified = false; }
    
    private int? _protectTime;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"protectTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int protectTime
    {
      get { return _protectTime?? default(int); }
      set { _protectTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool protectTimeSpecified
    {
      get { return this._protectTime != null; }
      set { if (value == (this._protectTime== null)) this._protectTime = value ? this.protectTime : (int?)null; }
    }
    private bool ShouldSerializeprotectTime() { return protectTimeSpecified; }
    private void ResetprotectTime() { protectTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}