//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAvaRecallMarch.proto
namespace PBMsgAvaRecallMarch
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAvaRecallMarch")]
  public partial class PBMsgAvaRecallMarch : global::ProtoBuf.IExtensible
  {
    public PBMsgAvaRecallMarch() {}
    
    private int _marchId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marchId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchId
    {
      get { return _marchId; }
      set { _marchId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}