//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgAVARelocate.proto
namespace PBMsgAVARelocate
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAVARelocate")]
  public partial class PBMsgAVARelocate : global::ProtoBuf.IExtensible
  {
    public PBMsgAVARelocate() {}
    
    private int _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _xCoord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"xCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xCoord
    {
      get { return _xCoord; }
      set { _xCoord = value; }
    }
    private int _yCoord;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"yCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int yCoord
    {
      get { return _yCoord; }
      set { _yCoord = value; }
    }
    private int _oldxCoord;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"oldxCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int oldxCoord
    {
      get { return _oldxCoord; }
      set { _oldxCoord = value; }
    }
    private int _oldyCoord;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"oldyCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int oldyCoord
    {
      get { return _oldyCoord; }
      set { _oldyCoord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}