//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: egs_event_resp.proto
namespace egs_event_resp
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sigpara")]
  public partial class sigpara : global::ProtoBuf.IExtensible
  {
    public sigpara() {}
    
    private string _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _val;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string val
    {
      get { return _val; }
      set { _val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"eventresp")]
  public partial class eventresp : IPacket
  {
    public eventresp() {}
	
	public int Opcode { get { return (int)PBOpcode.event_resp; } }
    
    private int _servierid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"servierid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int servierid
    {
      get { return _servierid; }
      set { _servierid = value; }
    }
    private int _playerid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private int _eventype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"eventype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int eventype
    {
      get { return _eventype; }
      set { _eventype = value; }
    }
    private int _eventid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"eventid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int eventid
    {
      get { return _eventid; }
      set { _eventid = value; }
    }
    private readonly global::System.Collections.Generic.List<sigpara> _extdatas = new global::System.Collections.Generic.List<sigpara>();
    [global::ProtoBuf.ProtoMember(5, Name=@"extdatas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<sigpara> extdatas
    {
      get { return _extdatas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}