//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: egs_nerror.proto
namespace egs_nerror
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"nerror")]
  public partial class nerror : IPacket
  {
    public nerror() {}
	
	public int Opcode { get { return (int)PBOpcode.nerror; } }
    
    private int _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private int? _popup;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"popup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int popup
    {
      get { return _popup?? default(int); }
      set { _popup = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool popupSpecified
    {
      get { return this._popup != null; }
      set { if (value == (this._popup== null)) this._popup = value ? this.popup : (int?)null; }
    }
    private bool ShouldSerializepopup() { return popupSpecified; }
    private void Resetpopup() { popupSpecified = false; }
    
    private int? _restart;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"restart", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int restart
    {
      get { return _restart?? default(int); }
      set { _restart = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool restartSpecified
    {
      get { return this._restart != null; }
      set { if (value == (this._restart== null)) this._restart = value ? this.restart : (int?)null; }
    }
    private bool ShouldSerializerestart() { return restartSpecified; }
    private void Resetrestart() { restartSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}