//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgWorldBossSocket.proto
namespace PBMsgWorldBossSocket
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgWorldBossSocket")]
  public partial class PBMsgWorldBossSocket : global::ProtoBuf.IExtensible
  {
    public PBMsgWorldBossSocket() {}
    
    private int? _bossId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bossId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bossId
    {
      get { return _bossId?? default(int); }
      set { _bossId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bossIdSpecified
    {
      get { return this._bossId != null; }
      set { if (value == (this._bossId== null)) this._bossId = value ? this.bossId : (int?)null; }
    }
    private bool ShouldSerializebossId() { return bossIdSpecified; }
    private void ResetbossId() { bossIdSpecified = false; }
    
    private int? _eventId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"eventId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int eventId
    {
      get { return _eventId?? default(int); }
      set { _eventId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool eventIdSpecified
    {
      get { return this._eventId != null; }
      set { if (value == (this._eventId== null)) this._eventId = value ? this.eventId : (int?)null; }
    }
    private bool ShouldSerializeeventId() { return eventIdSpecified; }
    private void ReseteventId() { eventIdSpecified = false; }
    
    private int? _bossTypeId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bossTypeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bossTypeId
    {
      get { return _bossTypeId?? default(int); }
      set { _bossTypeId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bossTypeIdSpecified
    {
      get { return this._bossTypeId != null; }
      set { if (value == (this._bossTypeId== null)) this._bossTypeId = value ? this.bossTypeId : (int?)null; }
    }
    private bool ShouldSerializebossTypeId() { return bossTypeIdSpecified; }
    private void ResetbossTypeId() { bossTypeIdSpecified = false; }
    
    private int? _xCoord;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"xCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xCoord
    {
      get { return _xCoord?? default(int); }
      set { _xCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool xCoordSpecified
    {
      get { return this._xCoord != null; }
      set { if (value == (this._xCoord== null)) this._xCoord = value ? this.xCoord : (int?)null; }
    }
    private bool ShouldSerializexCoord() { return xCoordSpecified; }
    private void ResetxCoord() { xCoordSpecified = false; }
    
    private int? _yCoord;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"yCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int yCoord
    {
      get { return _yCoord?? default(int); }
      set { _yCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool yCoordSpecified
    {
      get { return this._yCoord != null; }
      set { if (value == (this._yCoord== null)) this._yCoord = value ? this.yCoord : (int?)null; }
    }
    private bool ShouldSerializeyCoord() { return yCoordSpecified; }
    private void ResetyCoord() { yCoordSpecified = false; }
    
    private int? _blood;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"blood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int blood
    {
      get { return _blood?? default(int); }
      set { _blood = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bloodSpecified
    {
      get { return this._blood != null; }
      set { if (value == (this._blood== null)) this._blood = value ? this.blood : (int?)null; }
    }
    private bool ShouldSerializeblood() { return bloodSpecified; }
    private void Resetblood() { bloodSpecified = false; }
    
    private int? _direction;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int direction
    {
      get { return _direction?? default(int); }
      set { _direction = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool directionSpecified
    {
      get { return this._direction != null; }
      set { if (value == (this._direction== null)) this._direction = value ? this.direction : (int?)null; }
    }
    private bool ShouldSerializedirection() { return directionSpecified; }
    private void Resetdirection() { directionSpecified = false; }
    
    private int? _status;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status?? default(int); }
      set { _status = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool statusSpecified
    {
      get { return this._status != null; }
      set { if (value == (this._status== null)) this._status = value ? this.status : (int?)null; }
    }
    private bool ShouldSerializestatus() { return statusSpecified; }
    private void Resetstatus() { statusSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}