//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgMarchInfo.proto
namespace PBMsgMarchInfo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgMarchInfo")]
  public partial class PBMsgMarchInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgMarchInfo() {}
    
    private int? _marchId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"marchId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchId
    {
      get { return _marchId?? default(int); }
      set { _marchId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool marchIdSpecified
    {
      get { return this._marchId != null; }
      set { if (value == (this._marchId== null)) this._marchId = value ? this.marchId : (int?)null; }
    }
    private bool ShouldSerializemarchId() { return marchIdSpecified; }
    private void ResetmarchId() { marchIdSpecified = false; }
    
    private int? _fromPlayerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fromPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromPlayerId
    {
      get { return _fromPlayerId?? default(int); }
      set { _fromPlayerId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromPlayerIdSpecified
    {
      get { return this._fromPlayerId != null; }
      set { if (value == (this._fromPlayerId== null)) this._fromPlayerId = value ? this.fromPlayerId : (int?)null; }
    }
    private bool ShouldSerializefromPlayerId() { return fromPlayerIdSpecified; }
    private void ResetfromPlayerId() { fromPlayerIdSpecified = false; }
    
    private int? _fromX;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fromX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromX
    {
      get { return _fromX?? default(int); }
      set { _fromX = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromXSpecified
    {
      get { return this._fromX != null; }
      set { if (value == (this._fromX== null)) this._fromX = value ? this.fromX : (int?)null; }
    }
    private bool ShouldSerializefromX() { return fromXSpecified; }
    private void ResetfromX() { fromXSpecified = false; }
    
    private int? _fromY;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fromY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromY
    {
      get { return _fromY?? default(int); }
      set { _fromY = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromYSpecified
    {
      get { return this._fromY != null; }
      set { if (value == (this._fromY== null)) this._fromY = value ? this.fromY : (int?)null; }
    }
    private bool ShouldSerializefromY() { return fromYSpecified; }
    private void ResetfromY() { fromYSpecified = false; }
    
    private int? _toX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"toX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toX
    {
      get { return _toX?? default(int); }
      set { _toX = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toXSpecified
    {
      get { return this._toX != null; }
      set { if (value == (this._toX== null)) this._toX = value ? this.toX : (int?)null; }
    }
    private bool ShouldSerializetoX() { return toXSpecified; }
    private void ResettoX() { toXSpecified = false; }
    
    private int? _toY;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"toY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toY
    {
      get { return _toY?? default(int); }
      set { _toY = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toYSpecified
    {
      get { return this._toY != null; }
      set { if (value == (this._toY== null)) this._toY = value ? this.toY : (int?)null; }
    }
    private bool ShouldSerializetoY() { return toYSpecified; }
    private void ResettoY() { toYSpecified = false; }
    
    private int? _marchType;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"marchType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchType
    {
      get { return _marchType?? default(int); }
      set { _marchType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool marchTypeSpecified
    {
      get { return this._marchType != null; }
      set { if (value == (this._marchType== null)) this._marchType = value ? this.marchType : (int?)null; }
    }
    private bool ShouldSerializemarchType() { return marchTypeSpecified; }
    private void ResetmarchType() { marchTypeSpecified = false; }
    
    private int? _marchStatus;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"marchStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchStatus
    {
      get { return _marchStatus?? default(int); }
      set { _marchStatus = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool marchStatusSpecified
    {
      get { return this._marchStatus != null; }
      set { if (value == (this._marchStatus== null)) this._marchStatus = value ? this.marchStatus : (int?)null; }
    }
    private bool ShouldSerializemarchStatus() { return marchStatusSpecified; }
    private void ResetmarchStatus() { marchStatusSpecified = false; }
    
    private int? _startTimeStamp;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"startTimeStamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startTimeStamp
    {
      get { return _startTimeStamp?? default(int); }
      set { _startTimeStamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool startTimeStampSpecified
    {
      get { return this._startTimeStamp != null; }
      set { if (value == (this._startTimeStamp== null)) this._startTimeStamp = value ? this.startTimeStamp : (int?)null; }
    }
    private bool ShouldSerializestartTimeStamp() { return startTimeStampSpecified; }
    private void ResetstartTimeStamp() { startTimeStampSpecified = false; }
    
    private int? _endTimeStamp;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"endTimeStamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endTimeStamp
    {
      get { return _endTimeStamp?? default(int); }
      set { _endTimeStamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool endTimeStampSpecified
    {
      get { return this._endTimeStamp != null; }
      set { if (value == (this._endTimeStamp== null)) this._endTimeStamp = value ? this.endTimeStamp : (int?)null; }
    }
    private bool ShouldSerializeendTimeStamp() { return endTimeStampSpecified; }
    private void ResetendTimeStamp() { endTimeStampSpecified = false; }
    
    private int? _oneWayTime;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"oneWayTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int oneWayTime
    {
      get { return _oneWayTime?? default(int); }
      set { _oneWayTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool oneWayTimeSpecified
    {
      get { return this._oneWayTime != null; }
      set { if (value == (this._oneWayTime== null)) this._oneWayTime = value ? this.oneWayTime : (int?)null; }
    }
    private bool ShouldSerializeoneWayTime() { return oneWayTimeSpecified; }
    private void ResetoneWayTime() { oneWayTimeSpecified = false; }
    
    private int? _worldBossId;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"worldBossId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int worldBossId
    {
      get { return _worldBossId?? default(int); }
      set { _worldBossId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool worldBossIdSpecified
    {
      get { return this._worldBossId != null; }
      set { if (value == (this._worldBossId== null)) this._worldBossId = value ? this.worldBossId : (int?)null; }
    }
    private bool ShouldSerializeworldBossId() { return worldBossIdSpecified; }
    private void ResetworldBossId() { worldBossIdSpecified = false; }
    
    private int? _isWin;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"isWin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isWin
    {
      get { return _isWin?? default(int); }
      set { _isWin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool isWinSpecified
    {
      get { return this._isWin != null; }
      set { if (value == (this._isWin== null)) this._isWin = value ? this.isWin : (int?)null; }
    }
    private bool ShouldSerializeisWin() { return isWinSpecified; }
    private void ResetisWin() { isWinSpecified = false; }
    
    private int? _rallyId;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"rallyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rallyId
    {
      get { return _rallyId?? default(int); }
      set { _rallyId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rallyIdSpecified
    {
      get { return this._rallyId != null; }
      set { if (value == (this._rallyId== null)) this._rallyId = value ? this.rallyId : (int?)null; }
    }
    private bool ShouldSerializerallyId() { return rallyIdSpecified; }
    private void ResetrallyId() { rallyIdSpecified = false; }
    
    private int? _fromAllianceId;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"fromAllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromAllianceId
    {
      get { return _fromAllianceId?? default(int); }
      set { _fromAllianceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromAllianceIdSpecified
    {
      get { return this._fromAllianceId != null; }
      set { if (value == (this._fromAllianceId== null)) this._fromAllianceId = value ? this.fromAllianceId : (int?)null; }
    }
    private bool ShouldSerializefromAllianceId() { return fromAllianceIdSpecified; }
    private void ResetfromAllianceId() { fromAllianceIdSpecified = false; }
    
    private int? _toAllianceId;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"toAllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toAllianceId
    {
      get { return _toAllianceId?? default(int); }
      set { _toAllianceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toAllianceIdSpecified
    {
      get { return this._toAllianceId != null; }
      set { if (value == (this._toAllianceId== null)) this._toAllianceId = value ? this.toAllianceId : (int?)null; }
    }
    private bool ShouldSerializetoAllianceId() { return toAllianceIdSpecified; }
    private void ResettoAllianceId() { toAllianceIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}