//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgHeader.proto
namespace PBMsgHeader
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgHeader")]
  public partial class PBMsgHeader : global::ProtoBuf.IExtensible
  {
    public PBMsgHeader() {}
    
    private string _naId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"naId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string naId
    {
      get { return _naId; }
      set { _naId = value; }
    }
    private string _gcUid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gcUid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gcUid
    {
      get { return _gcUid; }
      set { _gcUid = value; }
    }
    private string _gcUnick;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gcUnick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gcUnick
    {
      get { return _gcUnick; }
      set { _gcUnick = value; }
    }
    private string _mobileId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"mobileId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mobileId
    {
      get { return _mobileId; }
      set { _mobileId = value; }
    }
    private int _platformId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"platformId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int platformId
    {
      get { return _platformId; }
      set { _platformId = value; }
    }
    private string _becomeUserId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"becomeUserId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string becomeUserId
    {
      get { return _becomeUserId; }
      set { _becomeUserId = value; }
    }
    private string _becomePassword;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"becomePassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string becomePassword
    {
      get { return _becomePassword; }
      set { _becomePassword = value; }
    }
    private int _debug;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"debug", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int debug
    {
      get { return _debug; }
      set { _debug = value; }
    }
    private string _gVer;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"gVer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gVer
    {
      get { return _gVer; }
      set { _gVer = value; }
    }
    private long _gameSlot;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"gameSlot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long gameSlot
    {
      get { return _gameSlot; }
      set { _gameSlot = value; }
    }
    private int _theme;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"theme", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int theme
    {
      get { return _theme; }
      set { _theme = value; }
    }
    private string _newLang;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"newLang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string newLang
    {
      get { return _newLang; }
      set { _newLang = value; }
    }
    private long _gameNumber;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"gameNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long gameNumber
    {
      get { return _gameNumber; }
      set { _gameNumber = value; }
    }
    private string _kabamId;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"kabamId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string kabamId
    {
      get { return _kabamId?? ""; }
      set { _kabamId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool kabamIdSpecified
    {
      get { return this._kabamId != null; }
      set { if (value == (this._kabamId== null)) this._kabamId = value ? this.kabamId : (string)null; }
    }
    private bool ShouldSerializekabamId() { return kabamIdSpecified; }
    private void ResetkabamId() { kabamIdSpecified = false; }
    
    private string _access_token;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string access_token
    {
      get { return _access_token?? ""; }
      set { _access_token = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool access_tokenSpecified
    {
      get { return this._access_token != null; }
      set { if (value == (this._access_token== null)) this._access_token = value ? this.access_token : (string)null; }
    }
    private bool ShouldSerializeaccess_token() { return access_tokenSpecified; }
    private void Resetaccess_token() { access_tokenSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}