//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgResponse.proto
namespace PBMsgResponse
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgResponse")]
  public partial class PBMsgResponse : global::ProtoBuf.IExtensible
  {
    public PBMsgResponse() {}
    
    private bool _ok;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ok", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ok
    {
      get { return _ok; }
      set { _ok = value; }
    }
    private int? _error_code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code?? default(int); }
      set { _error_code = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool error_codeSpecified
    {
      get { return this._error_code != null; }
      set { if (value == (this._error_code== null)) this._error_code = value ? this.error_code : (int?)null; }
    }
    private bool ShouldSerializeerror_code() { return error_codeSpecified; }
    private void Reseterror_code() { error_codeSpecified = false; }
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg?? ""; }
      set { _msg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool msgSpecified
    {
      get { return this._msg != null; }
      set { if (value == (this._msg== null)) this._msg = value ? this.msg : (string)null; }
    }
    private bool ShouldSerializemsg() { return msgSpecified; }
    private void Resetmsg() { msgSpecified = false; }
    
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data?? null; }
      set { _data = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dataSpecified
    {
      get { return this._data != null; }
      set { if (value == (this._data== null)) this._data = value ? this.data : (byte[])null; }
    }
    private bool ShouldSerializedata() { return dataSpecified; }
    private void Resetdata() { dataSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}