//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgLeaderboardReward.proto
namespace PBMsgLeaderboardReward
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgLeaderboardReward")]
  public partial class PBMsgLeaderboardReward : global::ProtoBuf.IExtensible
  {
    public PBMsgLeaderboardReward() {}
    
    private int _isGet;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isGet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isGet
    {
      get { return _isGet; }
      set { _isGet = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _itemList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> itemList
    {
      get { return _itemList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _itemNumList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"itemNumList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> itemNumList
    {
      get { return _itemNumList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}