//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgReqLeaderboard.proto
namespace PBMsgReqLeaderboard
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgReqLeaderboard")]
  public partial class PBMsgReqLeaderboard : global::ProtoBuf.IExtensible
  {
    public PBMsgReqLeaderboard() {}
    
    private int _leaderboardType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"leaderboardType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leaderboardType
    {
      get { return _leaderboardType; }
      set { _leaderboardType = value; }
    }
    private int _page;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }
    private int _pageSize;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pageSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pageSize
    {
      get { return _pageSize; }
      set { _pageSize = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _addIntData = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"addIntData", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> addIntData
    {
      get { return _addIntData; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _addStringData = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"addStringData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> addStringData
    {
      get { return _addStringData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}