//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgReqLeaderboardReward.proto
namespace PBMsgReqLeaderboardReward
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgReqLeaderboardReward")]
  public partial class PBMsgReqLeaderboardReward : global::ProtoBuf.IExtensible
  {
    public PBMsgReqLeaderboardReward() {}
    
    private int _leaderboardType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"leaderboardType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leaderboardType
    {
      get { return _leaderboardType; }
      set { _leaderboardType = value; }
    }
    private int _isGet;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isGet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isGet
    {
      get { return _isGet; }
      set { _isGet = value; }
    }
    private int _userId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _allianceId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"allianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int allianceId
    {
      get { return _allianceId; }
      set { _allianceId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}