//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgPveAllianceBossEvent.proto
namespace PBMsgPveAllianceBossEvent
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgPveAllianceBossEvent")]
  public partial class PBMsgPveAllianceBossEvent : global::ProtoBuf.IExtensible
  {
    public PBMsgPveAllianceBossEvent() {}
    
    private int? _actId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"actId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int actId
    {
      get { return _actId?? default(int); }
      set { _actId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool actIdSpecified
    {
      get { return this._actId != null; }
      set { if (value == (this._actId== null)) this._actId = value ? this.actId : (int?)null; }
    }
    private bool ShouldSerializeactId() { return actIdSpecified; }
    private void ResetactId() { actIdSpecified = false; }
    
    private long? _starttime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"starttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long starttime
    {
      get { return _starttime?? default(long); }
      set { _starttime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool starttimeSpecified
    {
      get { return this._starttime != null; }
      set { if (value == (this._starttime== null)) this._starttime = value ? this.starttime : (long?)null; }
    }
    private bool ShouldSerializestarttime() { return starttimeSpecified; }
    private void Resetstarttime() { starttimeSpecified = false; }
    
    private long? _endtime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"endtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long endtime
    {
      get { return _endtime?? default(long); }
      set { _endtime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool endtimeSpecified
    {
      get { return this._endtime != null; }
      set { if (value == (this._endtime== null)) this._endtime = value ? this.endtime : (long?)null; }
    }
    private bool ShouldSerializeendtime() { return endtimeSpecified; }
    private void Resetendtime() { endtimeSpecified = false; }
    
    private int? _status;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status?? default(int); }
      set { _status = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool statusSpecified
    {
      get { return this._status != null; }
      set { if (value == (this._status== null)) this._status = value ? this.status : (int?)null; }
    }
    private bool ShouldSerializestatus() { return statusSpecified; }
    private void Resetstatus() { statusSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<PBMsgPveAllianceBossEvent.Reward> _rewards = new global::System.Collections.Generic.List<PBMsgPveAllianceBossEvent.Reward>();
    [global::ProtoBuf.ProtoMember(5, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgPveAllianceBossEvent.Reward> rewards
    {
      get { return _rewards; }
    }
  
    private readonly global::System.Collections.Generic.List<PBMsgPveAllianceBossEvent.Reward> _playerRewards = new global::System.Collections.Generic.List<PBMsgPveAllianceBossEvent.Reward>();
    [global::ProtoBuf.ProtoMember(6, Name=@"playerRewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgPveAllianceBossEvent.Reward> playerRewards
    {
      get { return _playerRewards; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Reward")]
  public partial class Reward : global::ProtoBuf.IExtensible
  {
    public Reward() {}
    
    private int? _min;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"min", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int min
    {
      get { return _min?? default(int); }
      set { _min = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool minSpecified
    {
      get { return this._min != null; }
      set { if (value == (this._min== null)) this._min = value ? this.min : (int?)null; }
    }
    private bool ShouldSerializemin() { return minSpecified; }
    private void Resetmin() { minSpecified = false; }
    
    private int? _max;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max
    {
      get { return _max?? default(int); }
      set { _max = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool maxSpecified
    {
      get { return this._max != null; }
      set { if (value == (this._max== null)) this._max = value ? this.max : (int?)null; }
    }
    private bool ShouldSerializemax() { return maxSpecified; }
    private void Resetmax() { maxSpecified = false; }
    
    private int? _itemId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId?? default(int); }
      set { _itemId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemIdSpecified
    {
      get { return this._itemId != null; }
      set { if (value == (this._itemId== null)) this._itemId = value ? this.itemId : (int?)null; }
    }
    private bool ShouldSerializeitemId() { return itemIdSpecified; }
    private void ResetitemId() { itemIdSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}