//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgMergeServerChoice.proto
namespace PBMsgMergeServerChoice
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgMergeServerChoice")]
  public partial class PBMsgMergeServerChoice : global::ProtoBuf.IExtensible
  {
    public PBMsgMergeServerChoice() {}
    
    private int _saveServerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"saveServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int saveServerId
    {
      get { return _saveServerId; }
      set { _saveServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}