//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgReqServerMergeChoice.proto
namespace PBMsgReqServerMergeChoice
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgReqServerMergeChoice")]
  public partial class PBMsgReqServerMergeChoice : global::ProtoBuf.IExtensible
  {
    public PBMsgReqServerMergeChoice() {}
    
    private int _selectedServerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"selectedServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int selectedServerId
    {
      get { return _selectedServerId; }
      set { _selectedServerId = value; }
    }
    private int _targetServerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"targetServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetServerId
    {
      get { return _targetServerId; }
      set { _targetServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}