//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgReqMergeServer.proto
namespace PBMsgReqMergeServer
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgReqMergeServer")]
  public partial class PBMsgReqMergeServer : global::ProtoBuf.IExtensible
  {
    public PBMsgReqMergeServer() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}