//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgMapChange.proto
namespace PBMsgMapChange
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgMapChange")]
  public partial class PBMsgMapChange : global::ProtoBuf.IExtensible
  {
    public PBMsgMapChange() {}
    
    private int? _tileId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tileId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileId
    {
      get { return _tileId?? default(int); }
      set { _tileId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileIdSpecified
    {
      get { return this._tileId != null; }
      set { if (value == (this._tileId== null)) this._tileId = value ? this.tileId : (int?)null; }
    }
    private bool ShouldSerializetileId() { return tileIdSpecified; }
    private void ResettileId() { tileIdSpecified = false; }
    
    private int? _xCoord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"xCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xCoord
    {
      get { return _xCoord?? default(int); }
      set { _xCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool xCoordSpecified
    {
      get { return this._xCoord != null; }
      set { if (value == (this._xCoord== null)) this._xCoord = value ? this.xCoord : (int?)null; }
    }
    private bool ShouldSerializexCoord() { return xCoordSpecified; }
    private void ResetxCoord() { xCoordSpecified = false; }
    
    private int? _yCoord;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"yCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int yCoord
    {
      get { return _yCoord?? default(int); }
      set { _yCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool yCoordSpecified
    {
      get { return this._yCoord != null; }
      set { if (value == (this._yCoord== null)) this._yCoord = value ? this.yCoord : (int?)null; }
    }
    private bool ShouldSerializeyCoord() { return yCoordSpecified; }
    private void ResetyCoord() { yCoordSpecified = false; }
    
    private int? _status;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status?? default(int); }
      set { _status = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool statusSpecified
    {
      get { return this._status != null; }
      set { if (value == (this._status== null)) this._status = value ? this.status : (int?)null; }
    }
    private bool ShouldSerializestatus() { return statusSpecified; }
    private void Resetstatus() { statusSpecified = false; }
    
    private PBMsgMapChange.PBMsgTileData _tileData = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"tileData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgMapChange.PBMsgTileData tileData
    {
      get { return _tileData; }
      set { _tileData = value; }
    }
    private PBMsgMapChange.PBMsgUserInfo _userInfo = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"userInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgMapChange.PBMsgUserInfo userInfo
    {
      get { return _userInfo; }
      set { _userInfo = value; }
    }
    private PBMsgMapChange.PBMsgAllianceInfo _allianceInfo = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"allianceInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMsgMapChange.PBMsgAllianceInfo allianceInfo
    {
      get { return _allianceInfo; }
      set { _allianceInfo = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgTileData")]
  public partial class PBMsgTileData : global::ProtoBuf.IExtensible
  {
    public PBMsgTileData() {}
    
    private int? _tileId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tileId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileId
    {
      get { return _tileId?? default(int); }
      set { _tileId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileIdSpecified
    {
      get { return this._tileId != null; }
      set { if (value == (this._tileId== null)) this._tileId = value ? this.tileId : (int?)null; }
    }
    private bool ShouldSerializetileId() { return tileIdSpecified; }
    private void ResettileId() { tileIdSpecified = false; }
    
    private int? _xCoord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"xCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xCoord
    {
      get { return _xCoord?? default(int); }
      set { _xCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool xCoordSpecified
    {
      get { return this._xCoord != null; }
      set { if (value == (this._xCoord== null)) this._xCoord = value ? this.xCoord : (int?)null; }
    }
    private bool ShouldSerializexCoord() { return xCoordSpecified; }
    private void ResetxCoord() { xCoordSpecified = false; }
    
    private int? _yCoord;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"yCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int yCoord
    {
      get { return _yCoord?? default(int); }
      set { _yCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool yCoordSpecified
    {
      get { return this._yCoord != null; }
      set { if (value == (this._yCoord== null)) this._yCoord = value ? this.yCoord : (int?)null; }
    }
    private bool ShouldSerializeyCoord() { return yCoordSpecified; }
    private void ResetyCoord() { yCoordSpecified = false; }
    
    private int? _tileType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tileType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileType
    {
      get { return _tileType?? default(int); }
      set { _tileType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileTypeSpecified
    {
      get { return this._tileType != null; }
      set { if (value == (this._tileType== null)) this._tileType = value ? this.tileType : (int?)null; }
    }
    private bool ShouldSerializetileType() { return tileTypeSpecified; }
    private void ResettileType() { tileTypeSpecified = false; }
    
    private int? _orgTileLevel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"orgTileLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int orgTileLevel
    {
      get { return _orgTileLevel?? default(int); }
      set { _orgTileLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool orgTileLevelSpecified
    {
      get { return this._orgTileLevel != null; }
      set { if (value == (this._orgTileLevel== null)) this._orgTileLevel = value ? this.orgTileLevel : (int?)null; }
    }
    private bool ShouldSerializeorgTileLevel() { return orgTileLevelSpecified; }
    private void ResetorgTileLevel() { orgTileLevelSpecified = false; }
    
    private int? _tileLevel;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"tileLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileLevel
    {
      get { return _tileLevel?? default(int); }
      set { _tileLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileLevelSpecified
    {
      get { return this._tileLevel != null; }
      set { if (value == (this._tileLevel== null)) this._tileLevel = value ? this.tileLevel : (int?)null; }
    }
    private bool ShouldSerializetileLevel() { return tileLevelSpecified; }
    private void ResettileLevel() { tileLevelSpecified = false; }
    
    private int? _tileCityId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"tileCityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileCityId
    {
      get { return _tileCityId?? default(int); }
      set { _tileCityId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileCityIdSpecified
    {
      get { return this._tileCityId != null; }
      set { if (value == (this._tileCityId== null)) this._tileCityId = value ? this.tileCityId : (int?)null; }
    }
    private bool ShouldSerializetileCityId() { return tileCityIdSpecified; }
    private void ResettileCityId() { tileCityIdSpecified = false; }
    
    private int? _tileUserId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"tileUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileUserId
    {
      get { return _tileUserId?? default(int); }
      set { _tileUserId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileUserIdSpecified
    {
      get { return this._tileUserId != null; }
      set { if (value == (this._tileUserId== null)) this._tileUserId = value ? this.tileUserId : (int?)null; }
    }
    private bool ShouldSerializetileUserId() { return tileUserIdSpecified; }
    private void ResettileUserId() { tileUserIdSpecified = false; }
    
    private int? _tileAllianceId;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"tileAllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileAllianceId
    {
      get { return _tileAllianceId?? default(int); }
      set { _tileAllianceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileAllianceIdSpecified
    {
      get { return this._tileAllianceId != null; }
      set { if (value == (this._tileAllianceId== null)) this._tileAllianceId = value ? this.tileAllianceId : (int?)null; }
    }
    private bool ShouldSerializetileAllianceId() { return tileAllianceIdSpecified; }
    private void ResettileAllianceId() { tileAllianceIdSpecified = false; }
    
    private int? _tileProvinceId;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"tileProvinceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileProvinceId
    {
      get { return _tileProvinceId?? default(int); }
      set { _tileProvinceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileProvinceIdSpecified
    {
      get { return this._tileProvinceId != null; }
      set { if (value == (this._tileProvinceId== null)) this._tileProvinceId = value ? this.tileProvinceId : (int?)null; }
    }
    private bool ShouldSerializetileProvinceId() { return tileProvinceIdSpecified; }
    private void ResettileProvinceId() { tileProvinceIdSpecified = false; }
    
    private int? _tileBlockId;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"tileBlockId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileBlockId
    {
      get { return _tileBlockId?? default(int); }
      set { _tileBlockId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileBlockIdSpecified
    {
      get { return this._tileBlockId != null; }
      set { if (value == (this._tileBlockId== null)) this._tileBlockId = value ? this.tileBlockId : (int?)null; }
    }
    private bool ShouldSerializetileBlockId() { return tileBlockIdSpecified; }
    private void ResettileBlockId() { tileBlockIdSpecified = false; }
    
    private string _tileImgName;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"tileImgName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tileImgName
    {
      get { return _tileImgName?? ""; }
      set { _tileImgName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileImgNameSpecified
    {
      get { return this._tileImgName != null; }
      set { if (value == (this._tileImgName== null)) this._tileImgName = value ? this.tileImgName : (string)null; }
    }
    private bool ShouldSerializetileImgName() { return tileImgNameSpecified; }
    private void ResettileImgName() { tileImgNameSpecified = false; }
    
    private string _freezeEndTime;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"freezeEndTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string freezeEndTime
    {
      get { return _freezeEndTime?? ""; }
      set { _freezeEndTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool freezeEndTimeSpecified
    {
      get { return this._freezeEndTime != null; }
      set { if (value == (this._freezeEndTime== null)) this._freezeEndTime = value ? this.freezeEndTime : (string)null; }
    }
    private bool ShouldSerializefreezeEndTime() { return freezeEndTimeSpecified; }
    private void ResetfreezeEndTime() { freezeEndTimeSpecified = false; }
    
    private int? _carmot;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"carmot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int carmot
    {
      get { return _carmot?? default(int); }
      set { _carmot = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool carmotSpecified
    {
      get { return this._carmot != null; }
      set { if (value == (this._carmot== null)) this._carmot = value ? this.carmot : (int?)null; }
    }
    private bool ShouldSerializecarmot() { return carmotSpecified; }
    private void Resetcarmot() { carmotSpecified = false; }
    
    private int? _tileLv;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"tileLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileLv
    {
      get { return _tileLv?? default(int); }
      set { _tileLv = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileLvSpecified
    {
      get { return this._tileLv != null; }
      set { if (value == (this._tileLv== null)) this._tileLv = value ? this.tileLv : (int?)null; }
    }
    private bool ShouldSerializetileLv() { return tileLvSpecified; }
    private void ResettileLv() { tileLvSpecified = false; }
    
    private int? _cityType;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"cityType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cityType
    {
      get { return _cityType?? default(int); }
      set { _cityType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cityTypeSpecified
    {
      get { return this._cityType != null; }
      set { if (value == (this._cityType== null)) this._cityType = value ? this.cityType : (int?)null; }
    }
    private bool ShouldSerializecityType() { return cityTypeSpecified; }
    private void ResetcityType() { cityTypeSpecified = false; }
    
    private string _cityName;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"cityName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string cityName
    {
      get { return _cityName?? ""; }
      set { _cityName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cityNameSpecified
    {
      get { return this._cityName != null; }
      set { if (value == (this._cityName== null)) this._cityName = value ? this.cityName : (string)null; }
    }
    private bool ShouldSerializecityName() { return cityNameSpecified; }
    private void ResetcityName() { cityNameSpecified = false; }
    
    private bool? _misted;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"misted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool misted
    {
      get { return _misted?? default(bool); }
      set { _misted = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mistedSpecified
    {
      get { return this._misted != null; }
      set { if (value == (this._misted== null)) this._misted = value ? this.misted : (bool?)null; }
    }
    private bool ShouldSerializemisted() { return mistedSpecified; }
    private void Resetmisted() { mistedSpecified = false; }
    
    private int? _res_carmot;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"res_carmot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int res_carmot
    {
      get { return _res_carmot?? default(int); }
      set { _res_carmot = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool res_carmotSpecified
    {
      get { return this._res_carmot != null; }
      set { if (value == (this._res_carmot== null)) this._res_carmot = value ? this.res_carmot : (int?)null; }
    }
    private bool ShouldSerializeres_carmot() { return res_carmotSpecified; }
    private void Resetres_carmot() { res_carmotSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgUserInfo")]
  public partial class PBMsgUserInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgUserInfo() {}
    
    private int? _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId?? default(int); }
      set { _userId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool userIdSpecified
    {
      get { return this._userId != null; }
      set { if (value == (this._userId== null)) this._userId = value ? this.userId : (int?)null; }
    }
    private bool ShouldSerializeuserId() { return userIdSpecified; }
    private void ResetuserId() { userIdSpecified = false; }
    
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private int? _title;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int title
    {
      get { return _title?? default(int); }
      set { _title = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool titleSpecified
    {
      get { return this._title != null; }
      set { if (value == (this._title== null)) this._title = value ? this.title : (int?)null; }
    }
    private bool ShouldSerializetitle() { return titleSpecified; }
    private void Resettitle() { titleSpecified = false; }
    
    private string _might;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"might", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string might
    {
      get { return _might?? ""; }
      set { _might = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mightSpecified
    {
      get { return this._might != null; }
      set { if (value == (this._might== null)) this._might = value ? this.might : (string)null; }
    }
    private bool ShouldSerializemight() { return mightSpecified; }
    private void Resetmight() { mightSpecified = false; }
    
    private string _sex;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sex
    {
      get { return _sex?? ""; }
      set { _sex = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sexSpecified
    {
      get { return this._sex != null; }
      set { if (value == (this._sex== null)) this._sex = value ? this.sex : (string)null; }
    }
    private bool ShouldSerializesex() { return sexSpecified; }
    private void Resetsex() { sexSpecified = false; }
    
    private int? _warStatus;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"warStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int warStatus
    {
      get { return _warStatus?? default(int); }
      set { _warStatus = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool warStatusSpecified
    {
      get { return this._warStatus != null; }
      set { if (value == (this._warStatus== null)) this._warStatus = value ? this.warStatus : (int?)null; }
    }
    private bool ShouldSerializewarStatus() { return warStatusSpecified; }
    private void ResetwarStatus() { warStatusSpecified = false; }
    
    private int? _allianceId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"allianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int allianceId
    {
      get { return _allianceId?? default(int); }
      set { _allianceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool allianceIdSpecified
    {
      get { return this._allianceId != null; }
      set { if (value == (this._allianceId== null)) this._allianceId = value ? this.allianceId : (int?)null; }
    }
    private bool ShouldSerializeallianceId() { return allianceIdSpecified; }
    private void ResetallianceId() { allianceIdSpecified = false; }
    
    private int? _avatarId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"avatarId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int avatarId
    {
      get { return _avatarId?? default(int); }
      set { _avatarId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool avatarIdSpecified
    {
      get { return this._avatarId != null; }
      set { if (value == (this._avatarId== null)) this._avatarId = value ? this.avatarId : (int?)null; }
    }
    private bool ShouldSerializeavatarId() { return avatarIdSpecified; }
    private void ResetavatarId() { avatarIdSpecified = false; }
    
    private string _portraitName;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"portraitName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string portraitName
    {
      get { return _portraitName?? ""; }
      set { _portraitName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool portraitNameSpecified
    {
      get { return this._portraitName != null; }
      set { if (value == (this._portraitName== null)) this._portraitName = value ? this.portraitName : (string)null; }
    }
    private bool ShouldSerializeportraitName() { return portraitNameSpecified; }
    private void ResetportraitName() { portraitNameSpecified = false; }
    
    private string _badge;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"badge", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string badge
    {
      get { return _badge?? ""; }
      set { _badge = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool badgeSpecified
    {
      get { return this._badge != null; }
      set { if (value == (this._badge== null)) this._badge = value ? this.badge : (string)null; }
    }
    private bool ShouldSerializebadge() { return badgeSpecified; }
    private void Resetbadge() { badgeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgAllianceInfo")]
  public partial class PBMsgAllianceInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgAllianceInfo() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private string _might;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"might", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string might
    {
      get { return _might?? ""; }
      set { _might = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mightSpecified
    {
      get { return this._might != null; }
      set { if (value == (this._might== null)) this._might = value ? this.might : (string)null; }
    }
    private bool ShouldSerializemight() { return mightSpecified; }
    private void Resetmight() { mightSpecified = false; }
    
    private int? _leagues;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"leagues", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leagues
    {
      get { return _leagues?? default(int); }
      set { _leagues = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool leaguesSpecified
    {
      get { return this._leagues != null; }
      set { if (value == (this._leagues== null)) this._leagues = value ? this.leagues : (int?)null; }
    }
    private bool ShouldSerializeleagues() { return leaguesSpecified; }
    private void Resetleagues() { leaguesSpecified = false; }
    
    private string _curBanner;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"curBanner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string curBanner
    {
      get { return _curBanner?? ""; }
      set { _curBanner = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curBannerSpecified
    {
      get { return this._curBanner != null; }
      set { if (value == (this._curBanner== null)) this._curBanner = value ? this.curBanner : (string)null; }
    }
    private bool ShouldSerializecurBanner() { return curBannerSpecified; }
    private void ResetcurBanner() { curBannerSpecified = false; }
    
    private int? _curStyle;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"curStyle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int curStyle
    {
      get { return _curStyle?? default(int); }
      set { _curStyle = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curStyleSpecified
    {
      get { return this._curStyle != null; }
      set { if (value == (this._curStyle== null)) this._curStyle = value ? this.curStyle : (int?)null; }
    }
    private bool ShouldSerializecurStyle() { return curStyleSpecified; }
    private void ResetcurStyle() { curStyleSpecified = false; }
    
    private string _curStyleColor;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"curStyleColor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string curStyleColor
    {
      get { return _curStyleColor?? ""; }
      set { _curStyleColor = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curStyleColorSpecified
    {
      get { return this._curStyleColor != null; }
      set { if (value == (this._curStyleColor== null)) this._curStyleColor = value ? this.curStyleColor : (string)null; }
    }
    private bool ShouldSerializecurStyleColor() { return curStyleColorSpecified; }
    private void ResetcurStyleColor() { curStyleColorSpecified = false; }
    
    private int? _curSymbol;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"curSymbol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int curSymbol
    {
      get { return _curSymbol?? default(int); }
      set { _curSymbol = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curSymbolSpecified
    {
      get { return this._curSymbol != null; }
      set { if (value == (this._curSymbol== null)) this._curSymbol = value ? this.curSymbol : (int?)null; }
    }
    private bool ShouldSerializecurSymbol() { return curSymbolSpecified; }
    private void ResetcurSymbol() { curSymbolSpecified = false; }
    
    private string _curSymbolColor;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"curSymbolColor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string curSymbolColor
    {
      get { return _curSymbolColor?? ""; }
      set { _curSymbolColor = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curSymbolColorSpecified
    {
      get { return this._curSymbolColor != null; }
      set { if (value == (this._curSymbolColor== null)) this._curSymbolColor = value ? this.curSymbolColor : (string)null; }
    }
    private bool ShouldSerializecurSymbolColor() { return curSymbolColorSpecified; }
    private void ResetcurSymbolColor() { curSymbolColorSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}