//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgResourceTileInfo.proto
namespace PBMsgResourceTileInfo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgResourceTileInfo")]
  public partial class PBMsgResourceTileInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgResourceTileInfo() {}
    
    private int? _xCoord;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"xCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xCoord
    {
      get { return _xCoord?? default(int); }
      set { _xCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool xCoordSpecified
    {
      get { return this._xCoord != null; }
      set { if (value == (this._xCoord== null)) this._xCoord = value ? this.xCoord : (int?)null; }
    }
    private bool ShouldSerializexCoord() { return xCoordSpecified; }
    private void ResetxCoord() { xCoordSpecified = false; }
    
    private int? _yCoord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"yCoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int yCoord
    {
      get { return _yCoord?? default(int); }
      set { _yCoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool yCoordSpecified
    {
      get { return this._yCoord != null; }
      set { if (value == (this._yCoord== null)) this._yCoord = value ? this.yCoord : (int?)null; }
    }
    private bool ShouldSerializeyCoord() { return yCoordSpecified; }
    private void ResetyCoord() { yCoordSpecified = false; }
    
    private int? _resourceType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"resourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resourceType
    {
      get { return _resourceType?? default(int); }
      set { _resourceType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resourceTypeSpecified
    {
      get { return this._resourceType != null; }
      set { if (value == (this._resourceType== null)) this._resourceType = value ? this.resourceType : (int?)null; }
    }
    private bool ShouldSerializeresourceType() { return resourceTypeSpecified; }
    private void ResetresourceType() { resourceTypeSpecified = false; }
    
    private int? _amount;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int amount
    {
      get { return _amount?? default(int); }
      set { _amount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool amountSpecified
    {
      get { return this._amount != null; }
      set { if (value == (this._amount== null)) this._amount = value ? this.amount : (int?)null; }
    }
    private bool ShouldSerializeamount() { return amountSpecified; }
    private void Resetamount() { amountSpecified = false; }
    
    private int? _tileLv;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"tileLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileLv
    {
      get { return _tileLv?? default(int); }
      set { _tileLv = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tileLvSpecified
    {
      get { return this._tileLv != null; }
      set { if (value == (this._tileLv== null)) this._tileLv = value ? this.tileLv : (int?)null; }
    }
    private bool ShouldSerializetileLv() { return tileLvSpecified; }
    private void ResettileLv() { tileLvSpecified = false; }
    
    private string _occupant;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"occupant", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string occupant
    {
      get { return _occupant?? ""; }
      set { _occupant = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupantSpecified
    {
      get { return this._occupant != null; }
      set { if (value == (this._occupant== null)) this._occupant = value ? this.occupant : (string)null; }
    }
    private bool ShouldSerializeoccupant() { return occupantSpecified; }
    private void Resetoccupant() { occupantSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}