//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgGDS.proto
namespace PBMsgGDS
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgGDS")]
  public partial class PBMsgGDS : global::ProtoBuf.IExtensible
  {
    public PBMsgGDS() {}
    
    private string _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type?? ""; }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (string)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private int? _version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version?? default(int); }
      set { _version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool versionSpecified
    {
      get { return this._version != null; }
      set { if (value == (this._version== null)) this._version = value ? this.version : (int?)null; }
    }
    private bool ShouldSerializeversion() { return versionSpecified; }
    private void Resetversion() { versionSpecified = false; }
    
    private string _data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string data
    {
      get { return _data?? ""; }
      set { _data = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dataSpecified
    {
      get { return this._data != null; }
      set { if (value == (this._data== null)) this._data = value ? this.data : (string)null; }
    }
    private bool ShouldSerializedata() { return dataSpecified; }
    private void Resetdata() { dataSpecified = false; }
    
    private bool? _restart;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"restart", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool restart
    {
      get { return _restart?? default(bool); }
      set { _restart = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool restartSpecified
    {
      get { return this._restart != null; }
      set { if (value == (this._restart== null)) this._restart = value ? this.restart : (bool?)null; }
    }
    private bool ShouldSerializerestart() { return restartSpecified; }
    private void Resetrestart() { restartSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}