//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgReqBoostHero.proto
namespace PBMsgReqBoostHero
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgReqBoostHero")]
  public partial class PBMsgReqBoostHero : global::ProtoBuf.IExtensible
  {
    public PBMsgReqBoostHero() {}
    
    private long _hid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long hid
    {
      get { return _hid; }
      set { _hid = value; }
    }
    private int _iid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"iid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int iid
    {
      get { return _iid; }
      set { _iid = value; }
    }
    private int? _utimes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"utimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int utimes
    {
      get { return _utimes?? default(int); }
      set { _utimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool utimesSpecified
    {
      get { return this._utimes != null; }
      set { if (value == (this._utimes== null)) this._utimes = value ? this.utimes : (int?)null; }
    }
    private bool ShouldSerializeutimes() { return utimesSpecified; }
    private void Resetutimes() { utimesSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}