//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgHeroSkillLevelUpResult.proto
namespace PBMsgHeroSkillLevelUpResult
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgHeroSkillLevelUpResult")]
  public partial class PBMsgHeroSkillLevelUpResult : global::ProtoBuf.IExtensible
  {
    public PBMsgHeroSkillLevelUpResult() {}
    
    private long _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private int _skillLevel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"skillLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillLevel
    {
      get { return _skillLevel; }
      set { _skillLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}