//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgHeroInfo.proto
namespace PBMsgHeroInfo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgHeroInfo")]
  public partial class PBMsgHeroInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgHeroInfo() {}
    
    private int? _score;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score?? default(int); }
      set { _score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreSpecified
    {
      get { return this._score != null; }
      set { if (value == (this._score== null)) this._score = value ? this.score : (int?)null; }
    }
    private bool ShouldSerializescore() { return scoreSpecified; }
    private void Resetscore() { scoreSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}