//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgReqElevateHero.proto
namespace PBMsgReqElevateHero
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgReqElevateHero")]
  public partial class PBMsgReqElevateHero : global::ProtoBuf.IExtensible
  {
    public PBMsgReqElevateHero() {}
    
    private long _hid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long hid
    {
      get { return _hid; }
      set { _hid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}