//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgReqAssignHero.proto
namespace PBMsgReqAssignHero
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgReqAssignHero")]
  public partial class PBMsgReqAssignHero : global::ProtoBuf.IExtensible
  {
    public PBMsgReqAssignHero() {}
    
    private long _cid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long cid
    {
      get { return _cid; }
      set { _cid = value; }
    }
    private long _hid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long hid
    {
      get { return _hid; }
      set { _hid = value; }
    }
    private int _sid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}