//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgInitHeroExplore.proto
namespace PBMsgInitHeroExplore
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgInitHeroExplore")]
  public partial class PBMsgInitHeroExplore : global::ProtoBuf.IExtensible
  {
    public PBMsgInitHeroExplore() {}
    
    private long _exploreId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exploreId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long exploreId
    {
      get { return _exploreId; }
      set { _exploreId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _itemId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> itemId
    {
      get { return _itemId; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _itemCount = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"itemCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> itemCount
    {
      get { return _itemCount; }
    }
  
    private int _strength;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private PBMsgInitHeroExplore.PBMsgHeroStatus _status;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMsgInitHeroExplore.PBMsgHeroStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _sleepTime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"sleepTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sleepTime
    {
      get { return _sleepTime; }
      set { _sleepTime = value; }
    }
    private long _userHeroId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"userHeroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long userHeroId
    {
      get { return _userHeroId; }
      set { _userHeroId = value; }
    }
    private int? _strengthItemId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"strengthItemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int strengthItemId
    {
      get { return _strengthItemId?? default(int); }
      set { _strengthItemId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool strengthItemIdSpecified
    {
      get { return this._strengthItemId != null; }
      set { if (value == (this._strengthItemId== null)) this._strengthItemId = value ? this.strengthItemId : (int?)null; }
    }
    private bool ShouldSerializestrengthItemId() { return strengthItemIdSpecified; }
    private void ResetstrengthItemId() { strengthItemIdSpecified = false; }
    
    private int? _strengthItemCount;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"strengthItemCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int strengthItemCount
    {
      get { return _strengthItemCount?? default(int); }
      set { _strengthItemCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool strengthItemCountSpecified
    {
      get { return this._strengthItemCount != null; }
      set { if (value == (this._strengthItemCount== null)) this._strengthItemCount = value ? this.strengthItemCount : (int?)null; }
    }
    private bool ShouldSerializestrengthItemCount() { return strengthItemCountSpecified; }
    private void ResetstrengthItemCount() { strengthItemCountSpecified = false; }
    
    private int? _gemsN;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"gemsN", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gemsN
    {
      get { return _gemsN?? default(int); }
      set { _gemsN = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool gemsNSpecified
    {
      get { return this._gemsN != null; }
      set { if (value == (this._gemsN== null)) this._gemsN = value ? this.gemsN : (int?)null; }
    }
    private bool ShouldSerializegemsN() { return gemsNSpecified; }
    private void ResetgemsN() { gemsNSpecified = false; }
    
    [global::ProtoBuf.ProtoContract(Name=@"PBMsgHeroStatus")]
    public enum PBMsgHeroStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNLOCKED", Value=1)]
      UNLOCKED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IN_CITY_DO_NOTHING", Value=2)]
      IN_CITY_DO_NOTHING = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IN_CITY_IN_MARCH", Value=3)]
      IN_CITY_IN_MARCH = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IN_CITY_SLEEP", Value=4)]
      IN_CITY_SLEEP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IN_NO_CITY", Value=5)]
      IN_NO_CITY = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}