//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgReqPve.proto
namespace PBMsgReqPve
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgReqPve")]
  public partial class PBMsgReqPve : global::ProtoBuf.IExtensible
  {
    public PBMsgReqPve() {}
    
    private int? _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private int? _knightId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"knightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int knightId
    {
      get { return _knightId?? default(int); }
      set { _knightId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool knightIdSpecified
    {
      get { return this._knightId != null; }
      set { if (value == (this._knightId== null)) this._knightId = value ? this.knightId : (int?)null; }
    }
    private bool ShouldSerializeknightId() { return knightIdSpecified; }
    private void ResetknightId() { knightIdSpecified = false; }
    
    private int? _cityId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cityId
    {
      get { return _cityId?? default(int); }
      set { _cityId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cityIdSpecified
    {
      get { return this._cityId != null; }
      set { if (value == (this._cityId== null)) this._cityId = value ? this.cityId : (int?)null; }
    }
    private bool ShouldSerializecityId() { return cityIdSpecified; }
    private void ResetcityId() { cityIdSpecified = false; }
    
    private int? _marchId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"marchId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int marchId
    {
      get { return _marchId?? default(int); }
      set { _marchId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool marchIdSpecified
    {
      get { return this._marchId != null; }
      set { if (value == (this._marchId== null)) this._marchId = value ? this.marchId : (int?)null; }
    }
    private bool ShouldSerializemarchId() { return marchIdSpecified; }
    private void ResetmarchId() { marchIdSpecified = false; }
    
    private int? _levelId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"levelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelId
    {
      get { return _levelId?? default(int); }
      set { _levelId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelIdSpecified
    {
      get { return this._levelId != null; }
      set { if (value == (this._levelId== null)) this._levelId = value ? this.levelId : (int?)null; }
    }
    private bool ShouldSerializelevelId() { return levelIdSpecified; }
    private void ResetlevelId() { levelIdSpecified = false; }
    
    private bool? _instant;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"instant", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool instant
    {
      get { return _instant?? default(bool); }
      set { _instant = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool instantSpecified
    {
      get { return this._instant != null; }
      set { if (value == (this._instant== null)) this._instant = value ? this.instant : (bool?)null; }
    }
    private bool ShouldSerializeinstant() { return instantSpecified; }
    private void Resetinstant() { instantSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _units = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"units", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> units
    {
      get { return _units; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _heroId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(8, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> heroId
    {
      get { return _heroId; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _itemId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(9, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> itemId
    {
      get { return _itemId; }
    }
  
    private int? _leaderboardType;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"leaderboardType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leaderboardType
    {
      get { return _leaderboardType?? default(int); }
      set { _leaderboardType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool leaderboardTypeSpecified
    {
      get { return this._leaderboardType != null; }
      set { if (value == (this._leaderboardType== null)) this._leaderboardType = value ? this.leaderboardType : (int?)null; }
    }
    private bool ShouldSerializeleaderboardType() { return leaderboardTypeSpecified; }
    private void ResetleaderboardType() { leaderboardTypeSpecified = false; }
    
    private int? _chapterId;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chapterId
    {
      get { return _chapterId?? default(int); }
      set { _chapterId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool chapterIdSpecified
    {
      get { return this._chapterId != null; }
      set { if (value == (this._chapterId== null)) this._chapterId = value ? this.chapterId : (int?)null; }
    }
    private bool ShouldSerializechapterId() { return chapterIdSpecified; }
    private void ResetchapterId() { chapterIdSpecified = false; }
    
    private int? _page;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int page
    {
      get { return _page?? default(int); }
      set { _page = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pageSpecified
    {
      get { return this._page != null; }
      set { if (value == (this._page== null)) this._page = value ? this.page : (int?)null; }
    }
    private bool ShouldSerializepage() { return pageSpecified; }
    private void Resetpage() { pageSpecified = false; }
    
    private int? _pageSize;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"pageSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pageSize
    {
      get { return _pageSize?? default(int); }
      set { _pageSize = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pageSizeSpecified
    {
      get { return this._pageSize != null; }
      set { if (value == (this._pageSize== null)) this._pageSize = value ? this.pageSize : (int?)null; }
    }
    private bool ShouldSerializepageSize() { return pageSizeSpecified; }
    private void ResetpageSize() { pageSizeSpecified = false; }
    
    private int? _pveFte;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"pveFte", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pveFte
    {
      get { return _pveFte?? default(int); }
      set { _pveFte = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pveFteSpecified
    {
      get { return this._pveFte != null; }
      set { if (value == (this._pveFte== null)) this._pveFte = value ? this.pveFte : (int?)null; }
    }
    private bool ShouldSerializepveFte() { return pveFteSpecified; }
    private void ResetpveFte() { pveFteSpecified = false; }
    
    private string _allianceBossMsg;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"allianceBossMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string allianceBossMsg
    {
      get { return _allianceBossMsg?? ""; }
      set { _allianceBossMsg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool allianceBossMsgSpecified
    {
      get { return this._allianceBossMsg != null; }
      set { if (value == (this._allianceBossMsg== null)) this._allianceBossMsg = value ? this.allianceBossMsg : (string)null; }
    }
    private bool ShouldSerializeallianceBossMsg() { return allianceBossMsgSpecified; }
    private void ResetallianceBossMsg() { allianceBossMsgSpecified = false; }
    
    private int? _layerId;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"layerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int layerId
    {
      get { return _layerId?? default(int); }
      set { _layerId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool layerIdSpecified
    {
      get { return this._layerId != null; }
      set { if (value == (this._layerId== null)) this._layerId = value ? this.layerId : (int?)null; }
    }
    private bool ShouldSerializelayerId() { return layerIdSpecified; }
    private void ResetlayerId() { layerIdSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _buffItemId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(17, Name=@"buffItemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> buffItemId
    {
      get { return _buffItemId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}