//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgPveLeaderboard.proto
namespace PBMsgPveLeaderboard
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgPveLeaderboard")]
  public partial class PBMsgPveLeaderboard : global::ProtoBuf.IExtensible
  {
    public PBMsgPveLeaderboard() {}
    
    private int _total;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"total", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int total
    {
      get { return _total; }
      set { _total = value; }
    }
    private int _position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private long _score;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long score
    {
      get { return _score; }
      set { _score = value; }
    }
    private readonly global::System.Collections.Generic.List<PBMsgPveLeaderboard.PBMsgPveLeaderboardList> _data = new global::System.Collections.Generic.List<PBMsgPveLeaderboard.PBMsgPveLeaderboardList>();
    [global::ProtoBuf.ProtoMember(4, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgPveLeaderboard.PBMsgPveLeaderboardList> data
    {
      get { return _data; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgPveLeaderboardList")]
  public partial class PBMsgPveLeaderboardList : global::ProtoBuf.IExtensible
  {
    public PBMsgPveLeaderboardList() {}
    
    private int? _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId?? default(int); }
      set { _userId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool userIdSpecified
    {
      get { return this._userId != null; }
      set { if (value == (this._userId== null)) this._userId = value ? this.userId : (int?)null; }
    }
    private bool ShouldSerializeuserId() { return userIdSpecified; }
    private void ResetuserId() { userIdSpecified = false; }
    
    private long? _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long score
    {
      get { return _score?? default(long); }
      set { _score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreSpecified
    {
      get { return this._score != null; }
      set { if (value == (this._score== null)) this._score = value ? this.score : (long?)null; }
    }
    private bool ShouldSerializescore() { return scoreSpecified; }
    private void Resetscore() { scoreSpecified = false; }
    
    private string _displayName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"displayName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string displayName
    {
      get { return _displayName?? ""; }
      set { _displayName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool displayNameSpecified
    {
      get { return this._displayName != null; }
      set { if (value == (this._displayName== null)) this._displayName = value ? this.displayName : (string)null; }
    }
    private bool ShouldSerializedisplayName() { return displayNameSpecified; }
    private void ResetdisplayName() { displayNameSpecified = false; }
    
    private string _allianceName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"allianceName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string allianceName
    {
      get { return _allianceName?? ""; }
      set { _allianceName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool allianceNameSpecified
    {
      get { return this._allianceName != null; }
      set { if (value == (this._allianceName== null)) this._allianceName = value ? this.allianceName : (string)null; }
    }
    private bool ShouldSerializeallianceName() { return allianceNameSpecified; }
    private void ResetallianceName() { allianceNameSpecified = false; }
    
    private int? _allianceId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"allianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int allianceId
    {
      get { return _allianceId?? default(int); }
      set { _allianceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool allianceIdSpecified
    {
      get { return this._allianceId != null; }
      set { if (value == (this._allianceId== null)) this._allianceId = value ? this.allianceId : (int?)null; }
    }
    private bool ShouldSerializeallianceId() { return allianceIdSpecified; }
    private void ResetallianceId() { allianceIdSpecified = false; }
    
    private int? _might;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"might", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int might
    {
      get { return _might?? default(int); }
      set { _might = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mightSpecified
    {
      get { return this._might != null; }
      set { if (value == (this._might== null)) this._might = value ? this.might : (int?)null; }
    }
    private bool ShouldSerializemight() { return mightSpecified; }
    private void Resetmight() { mightSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}