//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgPveStaminaInfo.proto
namespace PBMsgPveStaminaInfo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgPveStaminaInfo")]
  public partial class PBMsgPveStaminaInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgPveStaminaInfo() {}
    
    private int? _energy;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int energy
    {
      get { return _energy?? default(int); }
      set { _energy = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool energySpecified
    {
      get { return this._energy != null; }
      set { if (value == (this._energy== null)) this._energy = value ? this.energy : (int?)null; }
    }
    private bool ShouldSerializeenergy() { return energySpecified; }
    private void Resetenergy() { energySpecified = false; }
    
    private long? _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time?? default(long); }
      set { _time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timeSpecified
    {
      get { return this._time != null; }
      set { if (value == (this._time== null)) this._time = value ? this.time : (long?)null; }
    }
    private bool ShouldSerializetime() { return timeSpecified; }
    private void Resettime() { timeSpecified = false; }
    
    private int? _recoverTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"recoverTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int recoverTime
    {
      get { return _recoverTime?? default(int); }
      set { _recoverTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool recoverTimeSpecified
    {
      get { return this._recoverTime != null; }
      set { if (value == (this._recoverTime== null)) this._recoverTime = value ? this.recoverTime : (int?)null; }
    }
    private bool ShouldSerializerecoverTime() { return recoverTimeSpecified; }
    private void ResetrecoverTime() { recoverTimeSpecified = false; }
    
    private int? _maxEnergy;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"maxEnergy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxEnergy
    {
      get { return _maxEnergy?? default(int); }
      set { _maxEnergy = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool maxEnergySpecified
    {
      get { return this._maxEnergy != null; }
      set { if (value == (this._maxEnergy== null)) this._maxEnergy = value ? this.maxEnergy : (int?)null; }
    }
    private bool ShouldSerializemaxEnergy() { return maxEnergySpecified; }
    private void ResetmaxEnergy() { maxEnergySpecified = false; }
    
    private int? _itemID;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"itemID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemID
    {
      get { return _itemID?? default(int); }
      set { _itemID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemIDSpecified
    {
      get { return this._itemID != null; }
      set { if (value == (this._itemID== null)) this._itemID = value ? this.itemID : (int?)null; }
    }
    private bool ShouldSerializeitemID() { return itemIDSpecified; }
    private void ResetitemID() { itemIDSpecified = false; }
    
    private int? _gem;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gem", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gem
    {
      get { return _gem?? default(int); }
      set { _gem = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool gemSpecified
    {
      get { return this._gem != null; }
      set { if (value == (this._gem== null)) this._gem = value ? this.gem : (int?)null; }
    }
    private bool ShouldSerializegem() { return gemSpecified; }
    private void Resetgem() { gemSpecified = false; }
    
    private int? _leftBuyNum;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"leftBuyNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leftBuyNum
    {
      get { return _leftBuyNum?? default(int); }
      set { _leftBuyNum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool leftBuyNumSpecified
    {
      get { return this._leftBuyNum != null; }
      set { if (value == (this._leftBuyNum== null)) this._leftBuyNum = value ? this.leftBuyNum : (int?)null; }
    }
    private bool ShouldSerializeleftBuyNum() { return leftBuyNumSpecified; }
    private void ResetleftBuyNum() { leftBuyNumSpecified = false; }
    
    private int? _advancedEnergy;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"advancedEnergy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int advancedEnergy
    {
      get { return _advancedEnergy?? default(int); }
      set { _advancedEnergy = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool advancedEnergySpecified
    {
      get { return this._advancedEnergy != null; }
      set { if (value == (this._advancedEnergy== null)) this._advancedEnergy = value ? this.advancedEnergy : (int?)null; }
    }
    private bool ShouldSerializeadvancedEnergy() { return advancedEnergySpecified; }
    private void ResetadvancedEnergy() { advancedEnergySpecified = false; }
    
    private int? _advancedItemPrice;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"advancedItemPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int advancedItemPrice
    {
      get { return _advancedItemPrice?? default(int); }
      set { _advancedItemPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool advancedItemPriceSpecified
    {
      get { return this._advancedItemPrice != null; }
      set { if (value == (this._advancedItemPrice== null)) this._advancedItemPrice = value ? this.advancedItemPrice : (int?)null; }
    }
    private bool ShouldSerializeadvancedItemPrice() { return advancedItemPriceSpecified; }
    private void ResetadvancedItemPrice() { advancedItemPriceSpecified = false; }
    
    private int? _advancedItemLeftBuyNum;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"advancedItemLeftBuyNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int advancedItemLeftBuyNum
    {
      get { return _advancedItemLeftBuyNum?? default(int); }
      set { _advancedItemLeftBuyNum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool advancedItemLeftBuyNumSpecified
    {
      get { return this._advancedItemLeftBuyNum != null; }
      set { if (value == (this._advancedItemLeftBuyNum== null)) this._advancedItemLeftBuyNum = value ? this.advancedItemLeftBuyNum : (int?)null; }
    }
    private bool ShouldSerializeadvancedItemLeftBuyNum() { return advancedItemLeftBuyNumSpecified; }
    private void ResetadvancedItemLeftBuyNum() { advancedItemLeftBuyNumSpecified = false; }
    
    private int? _advancedTime;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"advancedTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int advancedTime
    {
      get { return _advancedTime?? default(int); }
      set { _advancedTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool advancedTimeSpecified
    {
      get { return this._advancedTime != null; }
      set { if (value == (this._advancedTime== null)) this._advancedTime = value ? this.advancedTime : (int?)null; }
    }
    private bool ShouldSerializeadvancedTime() { return advancedTimeSpecified; }
    private void ResetadvancedTime() { advancedTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}