//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgPveInfo.proto
namespace PBMsgPveInfo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgPveInfo")]
  public partial class PBMsgPveInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgPveInfo() {}
    
    private int? _totalScore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"totalScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalScore
    {
      get { return _totalScore?? default(int); }
      set { _totalScore = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalScoreSpecified
    {
      get { return this._totalScore != null; }
      set { if (value == (this._totalScore== null)) this._totalScore = value ? this.totalScore : (int?)null; }
    }
    private bool ShouldSerializetotalScore() { return totalScoreSpecified; }
    private void ResettotalScore() { totalScoreSpecified = false; }
    
    private int? _totalStars;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"totalStars", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalStars
    {
      get { return _totalStars?? default(int); }
      set { _totalStars = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalStarsSpecified
    {
      get { return this._totalStars != null; }
      set { if (value == (this._totalStars== null)) this._totalStars = value ? this.totalStars : (int?)null; }
    }
    private bool ShouldSerializetotalStars() { return totalStarsSpecified; }
    private void ResettotalStars() { totalStarsSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<PBMsgPveInfo.PBMsgPveLevelInfo> _levelInfo = new global::System.Collections.Generic.List<PBMsgPveInfo.PBMsgPveLevelInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"levelInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgPveInfo.PBMsgPveLevelInfo> levelInfo
    {
      get { return _levelInfo; }
    }
  
    private byte[] _staminaInfo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"staminaInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] staminaInfo
    {
      get { return _staminaInfo?? null; }
      set { _staminaInfo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool staminaInfoSpecified
    {
      get { return this._staminaInfo != null; }
      set { if (value == (this._staminaInfo== null)) this._staminaInfo = value ? this.staminaInfo : (byte[])null; }
    }
    private bool ShouldSerializestaminaInfo() { return staminaInfoSpecified; }
    private void ResetstaminaInfo() { staminaInfoSpecified = false; }
    
    private byte[] _resultInfo;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"resultInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] resultInfo
    {
      get { return _resultInfo?? null; }
      set { _resultInfo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resultInfoSpecified
    {
      get { return this._resultInfo != null; }
      set { if (value == (this._resultInfo== null)) this._resultInfo = value ? this.resultInfo : (byte[])null; }
    }
    private bool ShouldSerializeresultInfo() { return resultInfoSpecified; }
    private void ResetresultInfo() { resultInfoSpecified = false; }
    
    private byte[] _marchInfo;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"marchInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] marchInfo
    {
      get { return _marchInfo?? null; }
      set { _marchInfo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool marchInfoSpecified
    {
      get { return this._marchInfo != null; }
      set { if (value == (this._marchInfo== null)) this._marchInfo = value ? this.marchInfo : (byte[])null; }
    }
    private bool ShouldSerializemarchInfo() { return marchInfoSpecified; }
    private void ResetmarchInfo() { marchInfoSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<PBMsgPveInfo.PBMsgPveHidenBossInfo> _hidenBossInfo = new global::System.Collections.Generic.List<PBMsgPveInfo.PBMsgPveHidenBossInfo>();
    [global::ProtoBuf.ProtoMember(7, Name=@"hidenBossInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgPveInfo.PBMsgPveHidenBossInfo> hidenBossInfo
    {
      get { return _hidenBossInfo; }
    }
  
    private long? _allianceBossEndTime;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"allianceBossEndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long allianceBossEndTime
    {
      get { return _allianceBossEndTime?? default(long); }
      set { _allianceBossEndTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool allianceBossEndTimeSpecified
    {
      get { return this._allianceBossEndTime != null; }
      set { if (value == (this._allianceBossEndTime== null)) this._allianceBossEndTime = value ? this.allianceBossEndTime : (long?)null; }
    }
    private bool ShouldSerializeallianceBossEndTime() { return allianceBossEndTimeSpecified; }
    private void ResetallianceBossEndTime() { allianceBossEndTimeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<PBMsgPveInfo.PBMsgPveSourceInfo> _sourceBossinfo = new global::System.Collections.Generic.List<PBMsgPveInfo.PBMsgPveSourceInfo>();
    [global::ProtoBuf.ProtoMember(9, Name=@"sourceBossinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMsgPveInfo.PBMsgPveSourceInfo> sourceBossinfo
    {
      get { return _sourceBossinfo; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgPveLevelInfo")]
  public partial class PBMsgPveLevelInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgPveLevelInfo() {}
    
    private int _levelID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"levelID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelID
    {
      get { return _levelID; }
      set { _levelID = value; }
    }
    private int? _highestScore;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"highestScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int highestScore
    {
      get { return _highestScore?? default(int); }
      set { _highestScore = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool highestScoreSpecified
    {
      get { return this._highestScore != null; }
      set { if (value == (this._highestScore== null)) this._highestScore = value ? this.highestScore : (int?)null; }
    }
    private bool ShouldSerializehighestScore() { return highestScoreSpecified; }
    private void ResethighestScore() { highestScoreSpecified = false; }
    
    private int? _highestStar;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"highestStar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int highestStar
    {
      get { return _highestStar?? default(int); }
      set { _highestStar = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool highestStarSpecified
    {
      get { return this._highestStar != null; }
      set { if (value == (this._highestStar== null)) this._highestStar = value ? this.highestStar : (int?)null; }
    }
    private bool ShouldSerializehighestStar() { return highestStarSpecified; }
    private void ResethighestStar() { highestStarSpecified = false; }
    
    private int? _highestSpeed;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"highestSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int highestSpeed
    {
      get { return _highestSpeed?? default(int); }
      set { _highestSpeed = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool highestSpeedSpecified
    {
      get { return this._highestSpeed != null; }
      set { if (value == (this._highestSpeed== null)) this._highestSpeed = value ? this.highestSpeed : (int?)null; }
    }
    private bool ShouldSerializehighestSpeed() { return highestSpeedSpecified; }
    private void ResethighestSpeed() { highestSpeedSpecified = false; }
    
    private int? _highestVitality;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"highestVitality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int highestVitality
    {
      get { return _highestVitality?? default(int); }
      set { _highestVitality = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool highestVitalitySpecified
    {
      get { return this._highestVitality != null; }
      set { if (value == (this._highestVitality== null)) this._highestVitality = value ? this.highestVitality : (int?)null; }
    }
    private bool ShouldSerializehighestVitality() { return highestVitalitySpecified; }
    private void ResethighestVitality() { highestVitalitySpecified = false; }
    
    private int? _highestTactics;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"highestTactics", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int highestTactics
    {
      get { return _highestTactics?? default(int); }
      set { _highestTactics = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool highestTacticsSpecified
    {
      get { return this._highestTactics != null; }
      set { if (value == (this._highestTactics== null)) this._highestTactics = value ? this.highestTactics : (int?)null; }
    }
    private bool ShouldSerializehighestTactics() { return highestTacticsSpecified; }
    private void ResethighestTactics() { highestTacticsSpecified = false; }
    
    private int? _lastScore;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"lastScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastScore
    {
      get { return _lastScore?? default(int); }
      set { _lastScore = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastScoreSpecified
    {
      get { return this._lastScore != null; }
      set { if (value == (this._lastScore== null)) this._lastScore = value ? this.lastScore : (int?)null; }
    }
    private bool ShouldSerializelastScore() { return lastScoreSpecified; }
    private void ResetlastScore() { lastScoreSpecified = false; }
    
    private int? _lastStar;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"lastStar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastStar
    {
      get { return _lastStar?? default(int); }
      set { _lastStar = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastStarSpecified
    {
      get { return this._lastStar != null; }
      set { if (value == (this._lastStar== null)) this._lastStar = value ? this.lastStar : (int?)null; }
    }
    private bool ShouldSerializelastStar() { return lastStarSpecified; }
    private void ResetlastStar() { lastStarSpecified = false; }
    
    private int? _lastSpeed;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"lastSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastSpeed
    {
      get { return _lastSpeed?? default(int); }
      set { _lastSpeed = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastSpeedSpecified
    {
      get { return this._lastSpeed != null; }
      set { if (value == (this._lastSpeed== null)) this._lastSpeed = value ? this.lastSpeed : (int?)null; }
    }
    private bool ShouldSerializelastSpeed() { return lastSpeedSpecified; }
    private void ResetlastSpeed() { lastSpeedSpecified = false; }
    
    private int? _lastVitality;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"lastVitality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastVitality
    {
      get { return _lastVitality?? default(int); }
      set { _lastVitality = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastVitalitySpecified
    {
      get { return this._lastVitality != null; }
      set { if (value == (this._lastVitality== null)) this._lastVitality = value ? this.lastVitality : (int?)null; }
    }
    private bool ShouldSerializelastVitality() { return lastVitalitySpecified; }
    private void ResetlastVitality() { lastVitalitySpecified = false; }
    
    private int? _lastTactics;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"lastTactics", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastTactics
    {
      get { return _lastTactics?? default(int); }
      set { _lastTactics = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastTacticsSpecified
    {
      get { return this._lastTactics != null; }
      set { if (value == (this._lastTactics== null)) this._lastTactics = value ? this.lastTactics : (int?)null; }
    }
    private bool ShouldSerializelastTactics() { return lastTacticsSpecified; }
    private void ResetlastTactics() { lastTacticsSpecified = false; }
    
    private int? _attackNum;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"attackNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attackNum
    {
      get { return _attackNum?? default(int); }
      set { _attackNum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool attackNumSpecified
    {
      get { return this._attackNum != null; }
      set { if (value == (this._attackNum== null)) this._attackNum = value ? this.attackNum : (int?)null; }
    }
    private bool ShouldSerializeattackNum() { return attackNumSpecified; }
    private void ResetattackNum() { attackNumSpecified = false; }
    
    private int? _attackNumPerDay;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"attackNumPerDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attackNumPerDay
    {
      get { return _attackNumPerDay?? default(int); }
      set { _attackNumPerDay = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool attackNumPerDaySpecified
    {
      get { return this._attackNumPerDay != null; }
      set { if (value == (this._attackNumPerDay== null)) this._attackNumPerDay = value ? this.attackNumPerDay : (int?)null; }
    }
    private bool ShouldSerializeattackNumPerDay() { return attackNumPerDaySpecified; }
    private void ResetattackNumPerDay() { attackNumPerDaySpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgPveHidenBossInfo")]
  public partial class PBMsgPveHidenBossInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgPveHidenBossInfo() {}
    
    private int _levelID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"levelID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelID
    {
      get { return _levelID; }
      set { _levelID = value; }
    }
    private long? _activeTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"activeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long activeTime
    {
      get { return _activeTime?? default(long); }
      set { _activeTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool activeTimeSpecified
    {
      get { return this._activeTime != null; }
      set { if (value == (this._activeTime== null)) this._activeTime = value ? this.activeTime : (long?)null; }
    }
    private bool ShouldSerializeactiveTime() { return activeTimeSpecified; }
    private void ResetactiveTime() { activeTimeSpecified = false; }
    
    private long? _curHP;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"curHP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long curHP
    {
      get { return _curHP?? default(long); }
      set { _curHP = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curHPSpecified
    {
      get { return this._curHP != null; }
      set { if (value == (this._curHP== null)) this._curHP = value ? this.curHP : (long?)null; }
    }
    private bool ShouldSerializecurHP() { return curHPSpecified; }
    private void ResetcurHP() { curHPSpecified = false; }
    
    private long? _totalHP;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"totalHP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long totalHP
    {
      get { return _totalHP?? default(long); }
      set { _totalHP = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalHPSpecified
    {
      get { return this._totalHP != null; }
      set { if (value == (this._totalHP== null)) this._totalHP = value ? this.totalHP : (long?)null; }
    }
    private bool ShouldSerializetotalHP() { return totalHPSpecified; }
    private void ResettotalHP() { totalHPSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgPveSourceInfo")]
  public partial class PBMsgPveSourceInfo : global::ProtoBuf.IExtensible
  {
    public PBMsgPveSourceInfo() {}
    
    private int _levelID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"levelID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelID
    {
      get { return _levelID; }
      set { _levelID = value; }
    }
    private long? _curHP;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"curHP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long curHP
    {
      get { return _curHP?? default(long); }
      set { _curHP = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curHPSpecified
    {
      get { return this._curHP != null; }
      set { if (value == (this._curHP== null)) this._curHP = value ? this.curHP : (long?)null; }
    }
    private bool ShouldSerializecurHP() { return curHPSpecified; }
    private void ResetcurHP() { curHPSpecified = false; }
    
    private long? _totalHP;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"totalHP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long totalHP
    {
      get { return _totalHP?? default(long); }
      set { _totalHP = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalHPSpecified
    {
      get { return this._totalHP != null; }
      set { if (value == (this._totalHP== null)) this._totalHP = value ? this.totalHP : (long?)null; }
    }
    private bool ShouldSerializetotalHP() { return totalHPSpecified; }
    private void ResettotalHP() { totalHPSpecified = false; }
    
    private long? _activeTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"activeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long activeTime
    {
      get { return _activeTime?? default(long); }
      set { _activeTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool activeTimeSpecified
    {
      get { return this._activeTime != null; }
      set { if (value == (this._activeTime== null)) this._activeTime = value ? this.activeTime : (long?)null; }
    }
    private bool ShouldSerializeactiveTime() { return activeTimeSpecified; }
    private void ResetactiveTime() { activeTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}