//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgReqWorldMap.proto
namespace PBMsgReqWorldMap
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgReqWorldMap")]
  public partial class PBMsgReqWorldMap : global::ProtoBuf.IExtensible
  {
    public PBMsgReqWorldMap() {}
    
    private int? _cmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cmd
    {
      get { return _cmd?? default(int); }
      set { _cmd = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cmdSpecified
    {
      get { return this._cmd != null; }
      set { if (value == (this._cmd== null)) this._cmd = value ? this.cmd : (int?)null; }
    }
    private bool ShouldSerializecmd() { return cmdSpecified; }
    private void Resetcmd() { cmdSpecified = false; }
    
    private int? _subcmd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"subcmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int subcmd
    {
      get { return _subcmd?? default(int); }
      set { _subcmd = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool subcmdSpecified
    {
      get { return this._subcmd != null; }
      set { if (value == (this._subcmd== null)) this._subcmd = value ? this.subcmd : (int?)null; }
    }
    private bool ShouldSerializesubcmd() { return subcmdSpecified; }
    private void Resetsubcmd() { subcmdSpecified = false; }
    
    private int? _xcoord;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"xcoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xcoord
    {
      get { return _xcoord?? default(int); }
      set { _xcoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool xcoordSpecified
    {
      get { return this._xcoord != null; }
      set { if (value == (this._xcoord== null)) this._xcoord = value ? this.xcoord : (int?)null; }
    }
    private bool ShouldSerializexcoord() { return xcoordSpecified; }
    private void Resetxcoord() { xcoordSpecified = false; }
    
    private int? _ycoord;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ycoord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ycoord
    {
      get { return _ycoord?? default(int); }
      set { _ycoord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ycoordSpecified
    {
      get { return this._ycoord != null; }
      set { if (value == (this._ycoord== null)) this._ycoord = value ? this.ycoord : (int?)null; }
    }
    private bool ShouldSerializeycoord() { return ycoordSpecified; }
    private void Resetycoord() { ycoordSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _tileId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"tileId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> tileId
    {
      get { return _tileId; }
    }
  
    private int? _itemId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId?? default(int); }
      set { _itemId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemIdSpecified
    {
      get { return this._itemId != null; }
      set { if (value == (this._itemId== null)) this._itemId = value ? this.itemId : (int?)null; }
    }
    private bool ShouldSerializeitemId() { return itemIdSpecified; }
    private void ResetitemId() { itemIdSpecified = false; }
    
    private int? _order;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int order
    {
      get { return _order?? default(int); }
      set { _order = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool orderSpecified
    {
      get { return this._order != null; }
      set { if (value == (this._order== null)) this._order = value ? this.order : (int?)null; }
    }
    private bool ShouldSerializeorder() { return orderSpecified; }
    private void Resetorder() { orderSpecified = false; }
    
    private int? _allianceId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"allianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int allianceId
    {
      get { return _allianceId?? default(int); }
      set { _allianceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool allianceIdSpecified
    {
      get { return this._allianceId != null; }
      set { if (value == (this._allianceId== null)) this._allianceId = value ? this.allianceId : (int?)null; }
    }
    private bool ShouldSerializeallianceId() { return allianceIdSpecified; }
    private void ResetallianceId() { allianceIdSpecified = false; }
    
    private int? _page;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int page
    {
      get { return _page?? default(int); }
      set { _page = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pageSpecified
    {
      get { return this._page != null; }
      set { if (value == (this._page== null)) this._page = value ? this.page : (int?)null; }
    }
    private bool ShouldSerializepage() { return pageSpecified; }
    private void Resetpage() { pageSpecified = false; }
    
    private int? _pageSize;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"pageSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pageSize
    {
      get { return _pageSize?? default(int); }
      set { _pageSize = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pageSizeSpecified
    {
      get { return this._pageSize != null; }
      set { if (value == (this._pageSize== null)) this._pageSize = value ? this.pageSize : (int?)null; }
    }
    private bool ShouldSerializepageSize() { return pageSizeSpecified; }
    private void ResetpageSize() { pageSizeSpecified = false; }
    
    private int? _toCityId;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"toCityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toCityId
    {
      get { return _toCityId?? default(int); }
      set { _toCityId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toCityIdSpecified
    {
      get { return this._toCityId != null; }
      set { if (value == (this._toCityId== null)) this._toCityId = value ? this.toCityId : (int?)null; }
    }
    private bool ShouldSerializetoCityId() { return toCityIdSpecified; }
    private void ResettoCityId() { toCityIdSpecified = false; }
    
    private int? _toMarchId;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"toMarchId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toMarchId
    {
      get { return _toMarchId?? default(int); }
      set { _toMarchId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toMarchIdSpecified
    {
      get { return this._toMarchId != null; }
      set { if (value == (this._toMarchId== null)) this._toMarchId = value ? this.toMarchId : (int?)null; }
    }
    private bool ShouldSerializetoMarchId() { return toMarchIdSpecified; }
    private void ResettoMarchId() { toMarchIdSpecified = false; }
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg?? ""; }
      set { _msg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool msgSpecified
    {
      get { return this._msg != null; }
      set { if (value == (this._msg== null)) this._msg = value ? this.msg : (string)null; }
    }
    private bool ShouldSerializemsg() { return msgSpecified; }
    private void Resetmsg() { msgSpecified = false; }
    
    private int? _actId;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"actId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int actId
    {
      get { return _actId?? default(int); }
      set { _actId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool actIdSpecified
    {
      get { return this._actId != null; }
      set { if (value == (this._actId== null)) this._actId = value ? this.actId : (int?)null; }
    }
    private bool ShouldSerializeactId() { return actIdSpecified; }
    private void ResetactId() { actIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}