//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PBMsgWorldMapSpeedUp.proto
namespace PBMsgWorldMapSpeedUp
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMsgWorldMapSpeedUp")]
  public partial class PBMsgWorldMapSpeedUp : global::ProtoBuf.IExtensible
  {
    public PBMsgWorldMapSpeedUp() {}
    
    private int _etaTimestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"etaTimestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int etaTimestamp
    {
      get { return _etaTimestamp; }
      set { _etaTimestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}